### ISSUE TITLE
E7.01 Create a new item in catalog of meals

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#1]
**As the Meal Designer, I want to create a new item in the meals catalog, so a meal can be added to the weekly plan.**

_1. Item editing creates a new version and new GUID for this item. 
2. Item editing/deleting does not affect meal plans which have this item already.
3. Only the last version items displayed in the catalog of meals.  

The data model is here https://www.draw.io/#G1iUM-tG41QntX_E00g3FxYm9ruNyJ6NZG  
Related Data Model objects: 

1. Meal
2. Ingredients
3. Units
4. Pictures
5. Videos
6. Tags
7. User
8.  #25 #
9. Category__

**Acceptance criteria:**

1. Follows the workflow in the MealPlanner Google Drive.
2. Ability to "see" the meal as the Client User will, prior to saving it.

**Comment by ElvinaCherepovich** [comment]
An administrator should be given the opportunity to edit a catalogue of meals.

**Comment by ElvinaCherepovich** [comment]
An administrator should be given the opportunity edit a catalogue of units.

**Comment by ElvinaCherepovich** [comment]
https://drive.google.com/drive/folders/1Bk_HjDmLa2UmF_BTAIhsdP_2y5mP-67f .

**Comment by ElvinaCherepovich** [comment]
https://www.draw.io/#G1iUM-tG41QntX_E00g3FxYm9ruNyJ6NZG .  DATA MODEL , use www.draw.io to open the schema

**Comment by Joycelyn2015** [comment]
This is DONE/COMPLETED.  Closing now.
