### ISSUE TITLE
E1.01 Create Meal Plans

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#10]
As meal designer, I want to add weekly meal plans to provide more client choices.
(Client User should have opportunity to choose up to 4 weekly plans).

Acceptance criteria:
Follows the workflow diagram on the MealPlanner Google Drive.

**Comment by Joycelyn2015** [comment]
Need to get Albert involved in completing this task.

**Comment by Joycelyn2015** [comment]
This is DONE/COMPLETED.  Closing now.
