### ISSUE TITLE
E1.03 Delete Meal Plans

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#11]
**As a Meal Designer, I want to delete/archive meal plans, so I can remove unpopular plans
 

1. Archived meals are marked as "Archive"  and showed as disabled (grey font) in catalogue of meals in an admin workspace. 
4. Client can not see archived items. 
2. The Mark "Archive" can be canceled. 
3. Archived meals can not be copied to a new plan from old plan which is used as a template. In this case client see a pop up window with a message that particular meal can not be copied bcoz it is does not exist . 
4. Archive does not create new version of item.  
5. Archived item can be edited. In this case, item will have new GUID and new version.

**Comment by Joycelyn2015** [comment]
Out of scope.
Closing.
