### ISSUE TITLE
Search for a meal plan by client ID

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#126]
As a user, I want to search for meal plans using the client as reference, so that I can base new meal plans on previous ones the client has used

The Client contains no personal info (name, contact info, etc.)
Search by Client ID only (same ID used in existing GreenerVillage system)

**Acceptance Criteria**
Returns the history of meal plans for that client
Show 4 most resent plans, with ability to search further into history
Show the week the plan was active for the client, as well as Meal Plan name (if it exists)
Displays the client ID on page after searching
Returns a "client not found" message when client does not exist

**Future Feature**
Search meal plans by client and use those plans for other clients

**Comment by sheenavaldez** [comment]
@albertlockett - I could not see this functionality in the latest release of Meal Planner. The only new feature available is "Client Assignment" on the Meal Designer page, which I cannot fully test as "Clients" need to be created. Please advise if I am missing anything. Thanks

**Comment by Joycelyn2015** [comment]
Look at the code.
The form is showing unassigned.
