### ISSUE TITLE
Shopping List Required Quantity

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#128]
**As a client, I want to see how much of each item/ingredient will be required for the week, so I can better plan my shopping**

For all meals in a given week, the ingredient quantities should be summed up and displayed to the client

**Acceptance Criteria**
The shopping list displays the required quantity needed for each item

**Future Features**
The quantity unit is set such that the quantity value does not end up being less than one or needlessly large if possible.  E.g. 100 grams is preferable to 0.1kg , 3 cups is preferable to 146 teaspoons

**Comment by silviamoreno** [comment]
As a client (this should be replaced by "customer"), I want to see how much of each item/ingredient will be required for the week, so I can better plan my shopping.
1. Client here refers to the GV client who has come in for help. The quantities themselves need to be generated based on the meal plan
Question:  Who plans the shopping list? If the user of the app is a GV staff creating a shopping list for the customer (GV client), then it is the GV staff you would have to be able to see the required quantities. The customer would see it from the staff screen or from the print out.

Acceptance Criteria: The shopping list displays the required quantity needed for each item .... (frequency?)
2. One shopping list per meal plan. That covers one week. Need a separate list each week
Question: Would it be better to complement at the end of the Acceptance Criteria:  ... "for each item selected for a specific week"
