### ISSUE TITLE
E7.07 Set availability of product at Food Bank

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#13]
As Meal Designer, I should be able to indicate/designate whether or not a product is available at the food bank, so that the client can be informed and plan their shopping accordingly

Acceptance Criteria: 
Scenario 1- Products are available, then I should be able to view the quantity of the products
Scenario 2- Products are not available, then I should get a notification of "unavailable"

Consideration:
If the products are unavailable, navigate to the order page

**Comment by shanthisa** [comment]
This does not seem to be a requirement in the current design. So closing this issue.
