### ISSUE TITLE
Verify the Nutrition Information format/granularity

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#139]
Verify with the Greener Village stakeholder/resource about the Nutrition Information format/granularity.
Please refer to Marco's UI
https://civictechfredericton.slack.com/files/U015Q7PM0TG/F01AJQ23FSA/nutrition.png

**For the first version, we'd like to have a 5-star nutrition rating (subjective, determined by the meal designer)**

**Comment by professordro** [comment]
Got in touch with GV and confirmed that they would like to do a simpler 5-star nutrition rating.
For now, the detailed nutrition info is not needed. Just a single nutrition rating attribute, 0-5, represented by stars in the UI

**Comment by Joycelyn2015** [comment]
Michael and Marco we able to discuss the requirements and changes that need to be done.

**Comment by Joycelyn2015** [comment]
This is DONE.  Closing now.
