### ISSUE TITLE
E7.01 Create new Product

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#14]
As the administrator, I want to create a new product, so it can be included in meals, shopping lists etc.

Attributes of a product include
Name/description
unit of measure
price
...

**Comment by Joycelyn2015** [comment]
There are 2 types of products:
- Generic food categories (e.g. carrots, potatoes, tomatoes)
- Food items sold in Supermarkets (e.g. Walmart)

**Comment by Joycelyn2015** [comment]
Duplicate of issue #54: E7.01 Add/Update/Archive item in Catalogue of Products
