### ISSUE TITLE
Document deployment steps (Linux)

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#165]
This is for Linux environment.

**Comment by Monty-Mason** [comment]
Tested!

![image.png](https://images.zenhubusercontent.com/5f849c05564a411872df7a87/cd1d1a2c-caf7-4ca1-9099-f6071d1d6c14)

Will move to Review/QA if anyone else is interested in reviewing. Otherwise, it can be closed!

**Comment by rorybray** [comment]
This has been tested enough times to be considered OK.  We can open new issues as problems arise.
