### ISSUE TITLE
Research on Unit Testing framework and GitLab implementation

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#176]
If we implement GitLab, what will be the impact to the current process?  Do we need to move out of Zenhub?

To implement unit testing, which framework will be best?  Which tools should we use to do unit testing?  What is the effort required?

**Comment by Monty-Mason** [comment]
I have added two files below. Please have a look.

The two files cover the following:

continuousDeployment_basicConclusions.txt - Integration of Gitlab and an alternative.
unitTesting_basicConclusions.txt - A small list of unit testing frameworks, and a very basic list of steps we would need to do to successfully implement them.

[continuousIntegrationDeployment_basicConclusions.txt](https://github.com/CivicTechFredericton/mealplanner/files/5948261/continuousIntegrationDeployment_basicConclusions.txt)
[unitTesting_basicConclusions.txt](https://github.com/CivicTechFredericton/mealplanner/files/5948263/unitTesting_basicConclusions.txt)

**Comment by Joycelyn2015** [comment]
not worth pursuing. closing this now.
