### ISSUE TITLE
Search by Person ID - No Person IDs in the Person ID dropdown

### ISSUE THREAD

**Issue by sheenavaldez** [CivicTechFredericton/mealplanner#177]
Steps:
1. Login to Meal Planner
2. On Home page, click the Filter icon (right above the Remove column)
3. Click the dropdown for Client ID
4. Edit a meal plan (click Edit icon)
5. On Meal Designer page, click Client Assignment icon
6. Click the dropdown button

Expected Result:
Client IDs are displayed

Actual Result:
No Client IDs in the Client ID dropdown on:
a. Home page - Filter
b. Meal Designer page - Client Assignment window

![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/d5fbc271-b32b-484e-95cb-26388887faf8)

![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/6119fc1c-b085-4a44-9d64-b60624abbbb3)

**Comment by professordro** [comment]
Client no longer to be used, the object is person.
personID is the assignment needed.
