### ISSUE TITLE
Form training - session 2

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#199]
Target end Apr

Topic
- wire the form into GraphQL

**Comment by Joycelyn2015** [comment]
Next Step:
to conduct another training next week. 
will post the schedule on slack.
target date: tues, april 27, 6pm
audience: colton, sayo, charles, shawn

**Comment by Joycelyn2015** [comment]
completed.
Attendees: Dan, Rori, Sayo, Colton, Mark
