### ISSUE TITLE
1 Maintain Mealplan

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#2]
**Create and maintain meal plans - the heart of the Meals Made Simple program
Stories in this epic mainly apply to the Green Village Meal Designer role.**

As a meal designer, I want to edit meal plans so I can create and improve them for the clients

A meal plan spans one week.
A meal plan has slots for breakfast lunch and dinner each day
A meal plan also has spots for Beverages, Desserts and Snacks that are not specific to a particular day
A meal plan has a default portion size based on the client household.

**Acceptance criteria:**
I should be able to search for meals, and then select them into the plan.
- Meals should be searchable by their attributes (name, description, etc.)
- Meals should be searchable by user defined tags (vegetarian, halal, gluten-free, etc.)
The plan is done on behalf of a specific client.
- Each plan is assigned to a specific week
- Multiple meal plans can be assigned to a single client and single week to support households where members eat different meals
A plan's creation date and author should be recorded.
Last update timestamp and author should be recorded when changes are made
The plan should be associated with the Client and searchable by client ID __(see Search for a Plan user story)__
Each plan should have a portion size and meals added to the plan are defaulted to that portion size.
Meals can be set to a different portion size within the plan if required
Portion size is in half-portion increments
Portion size cannot be zero
Slots within the plan (Breakfast, Lunch, Dinner, Snack, Beverage, Dessert) may be left blank
Breakfast Lunch and Dinner slots support zero or one meal
Snack Beverage and Dessert slots support between zero and ten meals

**Future Release**
Don't lose track of the original weekly plan. A modified plan (saved) should really be a new plan and have a new ID. Any plan can be marked as active or inactive (which decides whether it is made available to a client user). So we end up with every saved meal plan in the database with some active and some inactive.

Note, in future, when client users are allowed to make their own weekly plans from meals, If a meal, becomes inactive...the plans that contain that meal should also become inactive. E.g. a problem is discovered with a meal and it is not something we want a customer to select. The Meal Designer is going to have to know which weekly plans have been de-activated so they can substitute. 
OR
The Meal Designer cannot de-activate a meal without first substituting a new one. This may be easier...the rule would be that a meal cannot be deactivated if it belongs to one or more active weekly plans. Same should go for components of a meal: ingredients.

**Comment by rorybray** [comment]
Closed as complete and/or re-planning.
