### ISSUE TITLE
Reduce landing screen content

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#200]
Rori:

I think we should take away elements of the landing screen that will never be a thing. e.g. favourites, list of clients, catalogue of units and meal plan list. None make sense unless you're logged in. Consider redirecting unauthenticated users directly to the login screen also. Not talking about new designs here, just elimination and quick layout changes.

**Comment by sheenavaldez** [comment]
Could we hide Shopping List for now? Please remove Favorites and Settings from home page.
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/0cb83ec0-339c-4bff-a8d9-f2404a058f5c)

**Comment by sheenavaldez** [comment]
Retested and Passed.
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/2b5375a5-0dbf-4875-bd4b-7df6a3758bad)
