### ISSUE TITLE
Fix client/customer/person assignment

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#201]
Rori:

This applies to the meal plan list which shows "unassigned" even though it is assigned to a Person.  Change the header from "Client" to the agreed term. In the Meal Designer screen, the same problem exists, in the drop-down it shows (client: unassigned) and in the edit screen the meal plan has "undefined" suffix and the title again shows "This meal plan is unassigned". In the DB and schema this plan is, in fact, assigned to "User One".

**Comment by sheenavaldez** [comment]
Retested and Passed. Verified that Person ID dropdown (on home page) and Client Assignment dropdown (Designer page) now have values
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/ebe6545c-7e3b-4424-b17e-2b0b1a3ac1e7)
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/3a32d885-5695-4af7-9469-a5b677451454)
