### ISSUE TITLE
E3.01 Select one or more Meal Plans

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#21]
As a Client user, or acting on behalf of the client, I want to select one or more weekly meal plans so that I can organize my meals.

To manage the household, you can create multiple plans for a given week. Maximum 10.

Select plans for up to 4 future weeks. Multiple plans are assigned to upcoming weeks for a specific client.
(A week should start on a Monday) (The earliest week you can assign a meal plan to is the upcoming week)

Each meal plan needs to have portion selection. Granularity is half portions. Minimum is 0.5, Maximum is 10

**Acceptance Criteria:**
User is able to select/assign at least one weekly meal plan, up to 10 meals plans for one week.
User can scale the plan size by "half portions" per plan.
Meal Plan selections are assigned to the client, for future re-use.
Meal Plans cannot be assigned to the current week or to past weeks
Meal Plans can be duplicated from previous weeks into future weeks
Meal Plans can be created from scratch
Meal Plans are editable until they are no longer in the future

**Comment by Joycelyn2015** [comment]
Assigning to Shanti.

**Comment by Joycelyn2015** [comment]
Comments from Shanti:

1) What does ‘Meal Plan selections are assigned to the client, for future re-use.’ mean? can you please explain?

2) ‘Meal Plans can be created from scratch.’ It is already created from scratch now isn’t it? It is an existing feature isn’t it?

3) “Several requirements are combined into one ticket. Look at the acceptance criteria..User is able to select/assign at least one weekly meal plan, up to 10 meals plans for one week.” is one ticket. This would require adding two new tables. I would name them Schedule and Week.

4) “User can scale the plan size by “half portions” per plan.” needs to be a separate ticket. This would require adding a field scaling_factor in the table schedule. Apart from that it also would affect the view in Meal view and Shopping list. Probably this needs to be split to two tickets.

5) “Meal Plans cannot be assigned to the current week or to past weeks”. This is a separate ticket.

6) “Meal Plans are editable until they are no longer in the future”. This is a separate story. Does this mean “Previous week’s meal plan should not be editable.“?

**Comment by professordro** [comment]
Parking this ticket for a future release, at which time Shanthi's comments should be actioned to break it down into more appropriately sized tickets.

**Comment by shanthisa** [comment]
There is no such requirement mentioned by the client for now. So if it comes in future, we can recreate this issue. Closing this as of now.
