### ISSUE TITLE
#26 Shopping List - Tick box does not work 

### ISSUE THREAD

**Issue by Kris-tina** [CivicTechFredericton/mealplanner#222]
According to Acceptance criteria, "Each item should have a tick box to tick off while shopping". However, when I click on it nothing happens.

**Steps to Reproduce:**
On the Meal Plans page click on the Shopping Cart icon
On the shopping list page, click on a tick box. 

**Expected Result:** 
The tick box should check or uncheck as you click.

**Actual Result:**
Nothing happens

**Comment by shanthisa** [comment]
The tick box is just for display purpose only. It is meant for the customer to take a printout and tick it manually when they buy. It is not meant to check or uncheck in the app as this would involve saving it to the database which is not in the requirements.
