### ISSUE TITLE
Update-MealPlan

### ISSUE THREAD

**Issue by ShahidaRinku** [CivicTechFredericton/mealplanner#225]
without select 'Assignment' not possible to update meal plan data

**Comment by rorybray** [comment]
Can you describe the steps? I wasn't able to see the problem.

**Comment by ShahidaRinku** [comment]
I explain it step by step.
1. I Login as an Admin user.
2. Select 'Meal Designer'.
3. Select 'Perfect Meal (User Two)' under the Meal Plan.
4. Then I drag 'Coriander Coconut Chutney' under the Tuesday Breakfast. After I click the 'Save' button.
5. Meal plan does not update.
6. Again I select the 'Perfect Meal (User Two)' under the Meal Plan.
7. Then I drag 'Coriander Coconut Chutney' under the Tuesday Breakfast. 
8. I click the 'Assignment' button and click the 'Ok' button (didn't change the previous assignment)
9. After I click the 'Save' button.
10. Meal plan data update successfully.

I have one question, if I didn't interested to change the assignment, why I need to go to the assignment? I don't know, is it ok or not?

**Comment by rorybray** [comment]
No longer an issue
