### ISSUE TITLE
After editing and saving a Meal Plan, Meal Plan dropdown still shows old/previous Meal Plan

### ISSUE THREAD

**Issue by Kris-tina** [CivicTechFredericton/mealplanner#226]
When I edit a Meal Plan, save and then go to the "Meal Plan" dropdown menu, switch to another Meal Plan, and switch back
it still shows the old Meal Plan. 

Steps to Reproduce: 

1. Click MEALPLANNER to go Meal Plans page. 
2. Click on your desired Meal Plan from the list 
3. Add/Remove Meals to the Plan
4. Click Save 
5. Go to the Meal Plan dropdown menu
6. Switch to a different Meal Plan
7. Switch back to the Plan that you were editing

Expected Result:
Edited and saved Meal Plan should show
 
Actual Result:
Old Meal Plan is showing

**Comment by Charlie-OBrien** [comment]
This appears to be a browser caching issue.

**Comment by Charlie-OBrien** [comment]
In Chrome go to settings
Search for "cache"
Select "Cookies and other site data"
Click Clear data

**Comment by Joycelyn2015** [comment]
create a clean up function for graph sql
disengage the spinner.
build an outer container shell for logic (for the state change)
