### ISSUE TITLE
Meal Designer page > Duplicate meals are displayed in a cell

### ISSUE THREAD

**Issue by sheenavaldez** [CivicTechFredericton/mealplanner#239]
1. Go to Meal Designer page > click New
2. In the New Meal Plan window, fill out all required fields > click Save
3. Select a meal from the left navigation bar then, drag and drop to each cell or each box
4. Assign more than 1 meal to one cell, example: Breakfast box for Monday has 2-3 different meals
5. Click Save
6. Go to home page and open the newly created meal plan
 
Expected Result:
No duplicates are displayed
 
Actual Result:
Duplicate meals are displayed. See meal plan "Meal for Everyone" in the test environment
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/a311faaf-3050-4ef8-8f1a-5b3bbd7c1f30)

**Comment by shanthisa** [comment]
This doesn't happen as per the steps mentioned. Duplicate meals doesn't get created when new items are added to the same timeline. Duplicate gets created when Save button is clicked twice.
