### ISSUE TITLE
Shopping List > Blank page is displayed when meal plan is unassigned

### ISSUE THREAD

**Issue by sheenavaldez** [CivicTechFredericton/mealplanner#240]
1. Select an unassigned meal plan
2. Click the Shopping List icon
Test data:
"Meal Plan A  for Ms. Jane Doe" meal plan
 
Expected Result:
Shopping List is displayed without errors
  
Actual Result:
Blank page is displayed
http://mealplan-app-dev.s3-website-us-east-1.amazonaws.com/mealplans/7/shoppinglist

![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/07b2376f-b9e1-469f-a8b1-cdf1ad885eca)

**Comment by shanthisa** [comment]
This was fixed in #248 and I tested in testing server http://mealplan-app-dev.s3-website-us-east-1.amazonaws.com/mealplans/7/shoppinglist with meal plan "Meal Plan A for Ms. Jane Doe" and it works. So closing the issue
