### ISSUE TITLE
Enhancement - Display the username near the Logout button

### ISSUE THREAD

**Issue by sheenavaldez** [CivicTechFredericton/mealplanner#242]
When logged in as Admin or any user, display the username near the Logout button

**Comment by Joycelyn2015** [comment]
Can you please verify this if it complies to your design?  You may close this if needed.

**Comment by rmccaskill** [comment]
Decisions from tonight
Show the username THEN the user icon. Icon hover will highlight the icon and clicking will show a menu with only one item in the list: Logout. (No settings for now)

See Figma: https://www.figma.com/file/RP5Xa8kDT0CaJH98gnL6FL/Meal-Panner-Playground?node-id=54%3A41
![image](https://user-images.githubusercontent.com/1984709/145126711-f884fdbe-5598-47ab-89df-54c4317b97df.png)


Components to use

### Username in Header
Just text. See specs in Figma. Right aligned next to user icon

### User Icon in Header
IconButton  for the icon use AccountCircle for the icon  https://mui.com/components/material-icons/ 
AccountCircleIIcon for the icon.
See https://codesandbox.io/s/66rdk?file=/demo.js

### Menu
User https://mui.com/components/menus/ 
Use Icon menu!  and use LogoutIcon  for the icon
See https://codesandbox.io/s/4exxi?file=/demo.js
