### ISSUE TITLE
Estimate price does not change for newly added meals

### ISSUE THREAD

**Issue by Kris-tina** [CivicTechFredericton/mealplanner#246]
Step to reproduce: 
1. Go To Meal Designer
2. Create a new Meal Plan
3. Drug and drop for example (Baked Potatoes, Chicken Fajita Wraps, Chicken Salad Sandwich, Beef Stew, Battered Fish) to the calendar
4. Go to Shopping List, estimate price is $0.00

Expected Result: 
The estimated price should change
Actual Result:
The estimated price is $0.00

**Comment by shanthisa** [comment]
This is happening because there are no ingredients listed in baked potatoes, chicken Fajita wraps, chicken salad sandwich, beef stew and battered fish. If you add coriander coconut chutney or cucumber dill which has ingredients to the meal plan, the shopping list is generated.
