### ISSUE TITLE
E3.05 View Meal Nutrition

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#25]
As a Client User, I want to view meal nutrition information so that I know the health benefits and risks.

We should populate the tables directly with the nutrition information, and display on the page.
Refer to [Meal Recipe Wireframe](https://balsamiq.cloud/s1o6aik/pasbnaa/r9168)

Acceptance criteria:
1. Any nutritional summary must be correct.

2. For each meal, the Meal Designer will manually specify the info. 

**Future Features**
Weekly Meal Plan Nutritional Summary : But for a weekly plan, nutrition info will be calculated from summing that of the individual meals. However, if any of the meals is missing info, that info for the weekly pan should be shown as "unknown". In other words, any single missing field renders the sum invalid.
This is a fail-safe; all meals should have all fields filled in by the Meal Designer.

**Comment by Joycelyn2015** [comment]
We should populate the tables directly with the nutrition information, and display on the page.

**Comment by Joycelyn2015** [comment]
Marco: Created a React component for 5-star ratings

**Comment by Monty-Mason** [comment]
Tested - working.

**Future improvement suggestion:
- Display the nutritional information in a fashion similar to what we see on labels. We would be used to seeing that format the most visually. Right now, it is just a bunch of text, which is not very appealing to look at. At least making it look like, or somewhat similar to what we see on nutritional labels in the super markets, it will be easier for people to parse out the information quickly. Our brains are used to seeing that.**

**Comment by shanthisa** [comment]
Currently nutrition is not displayed in the meal. This is an epic which needs to be broken down into multiple issues. This can be part of the next release probably v3.
1. Design the nutrition of meal to be displayed as part of meal recipe page
2. Implement the design to render the nutrition
3. Long-term change: Bring React admin into the same main app based on role, and give an easy, user-friendly option to enter the nutrition values.
I would create these tickets after v2.

**Comment by shanthisa** [comment]
Implemented display of nutrition data of meal in  #614. So closing this issue.
