### ISSUE TITLE
Shopping List Items

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#26]
**As a client, I want a shopping list that shows all the items/ingredients I will need for the week, so I can obtain everything I need to make the week's meals**

The shopping list should contain all items required for 1-week of a client's meal plan(s).

The shopping list is generated by aggregating all the ingredients in all of the week's meals together.

Refer to [Shopping List Wireframe](https://www.figma.com/file/NNeo0yw9QmXlxYmlt6habS/Meal-Planner-Wireframe?node-id=18%3A10) for a visual aid in describing the shopping list (this is not a set-in-stone design)

**Acceptance criteria:**
Each item must be easy to identify and commonly available.
Each item should have a tick box to tick off while shopping.
A simple description of each item should be shown.
The list should be in an easy to read font, like Arial.
The list should be sorted by ingredient name alphabetically.

**Comment by professordro** [comment]
Change this into multiple stories
- one for ingredient list with tick boxes (Starting point, first story, first sprint)
- one for required quantities for the week
- one for regular retail prices
- one for total cost for the week

**Comment by julemlim** [comment]
Re. Acceptance Criteria:
- need to define the term "commonly available"; what if the item is not commonly available - should those be on a separate list or will not be displayed?
- "simple description" of item - may not be needed? or if still needed, what/who will be the source of this data/info?

**Comment by julemlim** [comment]
- An assumption could be made that the ingredients to be used by the meal designer are all commonly available.
- "simple description", per Mike, are those information that is useful on a shopping list  going to the store.

**Comment by rmccaskill** [comment]
Current design - Take a look at Shopping List - Master
Not a fully vetted design... Need we could save a lot of space/paper with other designs, but it's a start.

https://www.figma.com/file/RP5Xa8kDT0CaJH98gnL6FL/Meal-Panner-Playground?node-id=65%3A0
