### ISSUE TITLE
4 Create Shopping List

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#27]
**Summary:**
As a Customer, I want to create a shopping list of all the ingredients required for my meal plans.

**Description:**
Shopping lists are an aggregated set of Meal Items ("Products") that are generated from all the meals associated to a Customer for a given week. This will be displayed to the Customer by navigating to the Shopping List page using the "Shopping List" menu item, and selecting a Meal Plan from a drop down list of all Meal Plans for the Customer.  When the Customer selects a Meal Plan, a list of Products will appear below it

**Concerns:**

**Data Details:**
Upon entering the Shopping List page, the user will be prompted to select a Meal Plan from a dropdown list, which contains all assigned Meal Plans from their Meal Calendar. Upon selection, the page will pass that MealPlan ID to the database using a GraphQL query. 

The query will aggregate all Products used on the meals for the Meal Plan. The query will return a list of the Product Names.  This list will be sorted alphabetically by Product Name.

Once received by the page, the client side JS will bind the result list to a table object, with each row generated from each Product. This list will be displayed prominently to the Customer.

**Acceptance Criteria:**
- The page should be easily accessible by having a link directly of the main menu list.
- The ClientID should be visible on the page
- The date the list was generated should be visible on the page
- The list should be in an easy to read font, like Arial.
- All Products on the list are unique.
- Each Product in the list should have a tick box to tick off while shopping.
- The list should be viewable by ingredient name sorted alphabetically.
- The list should be viewable grouped according to shopping category (see story)
- The page should be Printable within the width of a letter page size, with >= 15mm margins. (refer to Print Shopping List story)

**Inputs:**
Customer ID [Client ID]
Meal Plan ID

**Outputs:**
List of: Product Name, sorted alphabetically by Product Name.

**Future Features**
Each item purchase quantity can be changed, but not less than zero.
User can print for up to 4 shopping lists for a 4-week plan.
Header shows which weekly meal plan(s) the list is generated from (as a convenient reference for the user). This will be useful when meal plans are named

**Deprecated requirements (no longer required)
- The Meal Plan the list was generated should be visible as a label on the page, not just in the drop down list.
- The portions should be visible on the page.
- Each Product must be easy to identify and commonly available. (this is controlled by the meal designers)

**Comment by Joycelyn2015** [comment]
Theme 2: Greener Village Client

**Comment by shanthisa** [comment]
The above commit is for backend of shopping list
