### ISSUE TITLE
E4.02 View Regular Retail Price

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#28]
**As a Client User, I want to see RRPs so that I do not overspend.**

**Acceptance criteria:**
Recommended Retail Price.
The RRP values will be populated directly into the tables by the meal designer.
This should be part of the shopping list.
Refer to [Shopping List Wireframe](https://www.figma.com/file/NNeo0yw9QmXlxYmlt6habS/Meal-Planner-Wireframe?node-id=18%3A10)

RRP can be sourced from a screen scrape, an API call, or a data file (e.g. csv) to be input into the system.
First version would require the meal designer to enter RRP and enter item size description for each entry.

**Future Features:**
Later, we can decide if we need to create a page where Meal Designer can input the RRP.
For Release 2, the Meal Designer should enter a RRP for each store product.
For Release 3, RRPs should be automatically populated by accessing store database(s).

**Background**
The RRPs should be realistic, not optimistic. The idea is to set a realistic expectation for what the client user will end up paying when they go shopping. We don't want to under-estimate or the client could run in to budgetary issues. Better if the client ends up paying a little less than MealPlanner forecasts. Under-promise, over-deliver.

**Comment by Joycelyn2015** [comment]
Recommended Retail Price.
The RRP values will be populated directly into the ables.
This should be part of the shopping list.

**Comment by shanthisa** [comment]
I have kind of brought in the products prices in the shopping list. Though it is not as described as in here, we have implemented the requirement of product price in a different way. So closing this issue.
