### ISSUE TITLE
E4.03 Edit Shopping List

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#29]
As a Client User, I want to edit my shopping list so that I change store product quantities.

Refer to [Shopping List Wireframe](https://balsamiq.cloud/s1o6aik/pasbnaa/r56BF)
- To be determined how this info is displayed - required quantity vs planned purchase quantity

Acceptance criteria:
1. Client cannot enter negative quantities.
2. Client can only decrease quantities.
3. Client cannot choose an unrealistic quantity, such as half an egg.
4. Quantity fields that have been changed from the original should be highlighted. So the client user can see which they have changed.

**Comment by professordro** [comment]
I need to discuss this with the team (and potentially with Greener Village). Not sure how to best work this into the shopping list.
Refer to this [Shopping List wireframe](https://balsamiq.cloud/s1o6aik/pasbnaa/r56BF/b7A08) as an example...

**Comment by rorybray** [comment]
Not applicable, GV would like a different approach, basically to check off items
