### ISSUE TITLE
E5.01 View Recipe and Instructions

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#32]
As a Meal Designer (on behalf of the customer), I want to be able to share detail on how to prepare each meal so the customer can follow the plan during the week.

The Meal Information page, or printed sheet, should contain the instructions on how to prepare.
Refer to [Meal Recipe Wireframe](https://www.figma.com/file/NNeo0yw9QmXlxYmlt6habS/Meal-Planner-Wireframe?node-id=18%3A16)

**Acceptance Criteria:**
User should be able to see the written instructions to prepare the meal.
Use standard "usability" guidelines for fonts and sizes and contrast to ensure the text is easy to read.
The Meal Info is easily printable / can be saved in pdf format

**Future Features**
User should be able to click and watch the preparation video. The place in the video should be remembered if the client disconnects part way through.

**Comment by pingpingnvhai** [comment]
*lean  - learn
The user should be able to search and select the recipe or instruction.
The content should be browser rendered

**Comment by rmccaskill** [comment]
My current proposal for this story.
See 'Meal Preparation Page' for visual layout.
 
https://www.figma.com/file/RP5Xa8kDT0CaJH98gnL6FL/Meal-Panner-Playground?node-id=111%3A10

**Comment by rmccaskill** [comment]
If you have questions or trouble accessing Figma, feel free to reach out.

**Comment by ColtonPatterson506** [comment]
Looking for some clarification on the issue. This is to be viewed by the Meal Designer through the admin interface, correct?

**Comment by professordro** [comment]
@ColtonPatterson506 , this story is more about how the meal recipe will appear when the greener village staff is showing it to their client.  They should also be able to print or save as PDF to email to their client.

**Comment by rorybray** [comment]
Right. Remember that the admin interface is going to go away and clients/customers wouldn't ever see it anyway.
