### ISSUE TITLE
Empty meal is being created in admin-ui

### ISSUE THREAD

**Issue by rohinikcanada** [CivicTechFredericton/mealplanner#355]
In admin-ui, while creating meal I have noticed that,  even when all the fields are empty and I click on 'Save' button. It shows 'the element is created'.

Steps to Reproduce:

1. Login to "http://localhost:3000/#/login"
2. Clicked on 'Create' button, to create new meal.
3. Left all the fields empty and clicked 'Save' button

Expected: Error should be thrown to pass mandatory values
Actual :  Popup with text Meal plan created is displayed

**Comment by myworldinme** [comment]
Good afternoon ma,

Should I validate all the inputs and enforce the mandatory values before
allowing the creation of a meal plan?

Thank you
Best regards,

Aisida

**Comment by valentim82** [comment]
These are the mandatory field: 
code
name_en

as per 004-meal.sql

**Comment by RLCASTRO** [comment]
As @valentim82 mentioned, there are two 'not null' fields in the meals table. However, I believe having a minimum amount of information in the database is reasonable. So, I added a client-level validation when creating or editing meals for the following fields:
  * code
  * nameEn
  * nameFr
  * descriptionEn
  * descriptionFr
  * categories

![image](https://github.com/CivicTechFredericton/mealplanner/assets/37277959/01fd9417-cff9-40aa-8b1b-0897b2099c82)

What do you think @shanthisa ? Can I keep it like this?

**Comment by RLCASTRO** [comment]
> In admin-ui, while creating meal I have noticed that, even when all the fields are empty and I click on 'Save' button. It shows 'the element is created'.
> 
> Steps to Reproduce:
> 
> 1. Login to "http://localhost:3000/#/login"
> 2. Clicked on 'Create' button, to create new meal.
> 3. Left all the fields empty and clicked 'Save' button
> 
> Expected: Error should be thrown to pass mandatory values Actual : Popup with text Meal plan created is displayed

> [!IMPORTANT]
Just a small update here, the step 1 must be at port 2000: Login to "http://localhost:2000/#/login"

**Comment by olamakhlouf** [comment]
QA is Done.
Test case [AA-CreateEmptyMeal-075](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-CreateEmptyMeal-075) : Passed with comment

**Comment by RLCASTRO** [comment]
Hi @olamakhlouf. Can you update the test case with the following steps and test it again, please?

1. Access to the Admin UI as an admin.
2. Leave the `Name en` field blank
3. Insert any character in any other field to enable the save button
4. leave all the other fields blank.
5. Click on the "create" button.
6. Verify that no meal is created without the minimum requirement which is the `Name en` field.

This should return an error and not allow creating new meals without the required field, as in the image below:


![Image](https://github.com/CivicTechFredericton/mealplanner/assets/37277959/a85b0d71-c838-4e9c-83db-677f8cc3e51b)

**Comment by olamakhlouf** [comment]
Thanks @RLCASTRO 
updated the test case
Test case: Passed

**Comment by RLCASTRO** [comment]
Thanks @olamakhlouf . Test case reviewed. LGTM 👍. Can you please close the issue @shanthisa?
