### ISSUE TITLE
User ID not necessary

### ISSUE THREAD

**Issue by BawbSmith** [CivicTechFredericton/mealplanner#358]
I can create a meal plan without a user id as it is not a required * field. Is this a problem? I would prefer it that way. I don't need to know I created all plans.

I would not fix it. Not my decision tho.

**Comment by shanthisa** [comment]
Yes. It is possible to create a meal plan without user id. That is for creating templates which can be reassigned later. We plan to implement dupicate meal plans from the existing meal plan. When we implement that, this feature will be more evident. Duplicate meal plan is a feature we will implement after this MVP.
