### ISSUE TITLE
E1.04 Edit Ingredients

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#37]
As a meal designer, I want to edit ingredients and their quantities so that I can improve a meal plan

**Comment by shanthisa** [comment]
What is catalog of units ? Is catalog of products the ingredients list?

**Comment by shanthisa** [comment]
Is there UI designs for these requirements?

**Comment by professordro** [comment]
This story no longer aligns to our epics.
The closest are [#102 Add/Update Recipe](https://app.zenhub.com/workspaces/mealplanner-5df0313f541828745932eb9c/issues/civictechfredericton/mealplanner/102)
and [#54 Add/update item in catalog of products](https://app.zenhub.com/workspaces/mealplanner-5df0313f541828745932eb9c/issues/civictechfredericton/mealplanner/54)
This story will need to be cancelled.
