### ISSUE TITLE
Searching Plans - how?

### ISSUE THREAD

**Issue by BawbSmith** [CivicTechFredericton/mealplanner#370]
Suppose user has 50 plans on screen, all with unique plan names. 
How will user find a plan? By name? Extremely hard trying to remember so many names. 
User will search and search trying to find a plan.

We must train them to identify plan names as 'Client #    Week #'. 
This will give immediate search results. All plans for 1 client or all plans for a given week (I've identified my workload). 
Train them to use actual (abbreviated) meal names as tags - more meaningful than a generic plan name or generic tag.
Train them to use Description as 'Comments' allowing user to comment on the plan while creating it and then follow-up comments.
These comments don't need to be on shopping list.

**Comment by shanthisa** [comment]
I think the meal plan name is a good suggestion. This can be done by giving a tooltip or as a (short i icon) that says 'Suggestion: Client # Week #' for meal plan name while creating.
For mealplan tags, Greener Village had communicated to me what they intend to use and we are providing a filter by tag for the mealplan in  #509
Also my suggestion for description tooltip is 
'Notes on the discussion with client about their requirements, your suggestions.'

Addressed first and third suggestion in #518.
