### ISSUE TITLE
Search meal plan

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#372]
Based on any word of the name in the meal plan, provide the search results.

**Comment by shanthisa** [comment]
I completed the QA. So closing the issue.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-MPSearch-013](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0/_edit#related-bug-id-372) : Passed
