### ISSUE TITLE
Duplicate meal plan

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#377]
Create a meal plan from an existing meal plan.

**Comment by shanthisa** [comment]
@ala-sk98 - Can you please test this?

**Comment by ala-sk98** [comment]
> @ala-sk98 - Can you please test this?

Sure, will work on it.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-DuplicateMealPlan-020](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-duplicatemealplan-020) : Passed
