### ISSUE TITLE
Duplicate meal is being created in admin-ui

### ISSUE THREAD

**Issue by rohinikcanada** [CivicTechFredericton/mealplanner#379]
I'm able to create the duplicate meal 'Millet Dosa' in admin-ui, even though 'Millet Dosa' already exists in the meals list.

Steps to Reproduce:
------------------
1. Visit 'http://localhost:3000
2. Enter Username and Password
3. Click on 'Create' in meals page
4. Enter Meal name: Millet Dosa,  Description, Video URL, etc.
5. Click on 'Save' button

Result:
-------

Expected: Millet Dosa already exists.
Actual: Element is created

**Comment by shanthisa** [comment]
This is not a bug. there is no such requirement for the meals to be unique. We can have multiple meals with the same name. If GV requests for it we can implement.
