### ISSUE TITLE
Questions for the future.

### ISSUE THREAD

**Issue by BawbSmith** [CivicTechFredericton/mealplanner#383]
The test site now has 275 products added with more to come. Awesome. Was this done by trainees or staff getting to know process?
I was wrong, Nutrition does need 42 fields. I thought it could be reduced...it can't.
Do they need Nutrition values for each product? (42x275 fields). 
Meals need all fields, but I'm not convinced Products need 15,000 fields and counting. How is Product Nutrient info being used?
We need nutrition for the Potato Casserole. Do we need it for the Pea in the dish? How is that info going to be used?

**Comment by shanthisa** [comment]
No actual feature request or bug determined. This was more of a question that was clarified
