### ISSUE TITLE
E2.02 Add Videos*

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#41]
As a Meal Designer, I want to add videos so that clients can watch how to prepare the meal.  Provide the URL of the videos.

For Release 1, URL to videos will be populated into the tables.

This user story is moved to Release 2.  This requires creation of UI where Meal Designer can create/update/delete URL to videos (that provide instructions to prepare the meals).

**Comment by Joycelyn2015** [comment]
This feature is part of another story.
We can close this.
