### ISSUE TITLE
[BUG] Error message is not displayed when you hit enter while using invalid credentials

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#413]
**Describe the bug**
In the Login page, when invalid credentials are given and enter button is hit, the error message is not displayed.

**To Reproduce**
1. Go to 'Login page' of meal planner app.
2. Give invalid credentials such as 'admin' for username and 'pass' for password.
3. Press 'enter' (return) key.
4. There is no indication that the login failed. i.e. no error message is displayed.

**Expected behavior**
When login fails due to wrong credentials and enter is pressed, error message that the credentials are wrong should be displayed.

**Test Environment (please complete the following information):**
 - Chrome
 - All platforms

**Comment by shanthisa** [comment]
@ala-sk98 can you please test this?

**Comment by ala-sk98** [comment]
QA done.
Test case[MP-LoginErrorDisplay-019](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-loginerrordisplay-019) : Passed

**Comment by shanthisa** [comment]
LGTM 👍
