### ISSUE TITLE
Deleting a meal from the meals table throws an error foreign key constraint

### ISSUE THREAD

**Issue by arhtivap** [CivicTechFredericton/mealplanner#426]
**Describe the bug**
In Admin-UI, when I try to delete a meal from the meals table, instead of getting deleted it throws me an error "foreign key constraint"

**To Reproduce**
Steps to reproduce the behaviour:
    1. Go to https://goodmealplan.com
    2. Click Meals
    3. Click on the checkbox next to the id 
    4. Click 'Delete'
    5. It should delete a meal instead it throws an error

**Expected behaviour**
The selected meal entry should be deleted

**Test Environment (please complete the following information):**
 - Chrome
 - Mac OSX

**Comment by shanthisa** [comment]
@ala-sk98  - Priya says this is not reproducible. I remember putting a cascade long ago. So ideally this issue should not occur. But I would like you to test it before we close this issue as not reproducible.

**Comment by ala-sk98** [comment]
QA done.
Test case [AA-DeleteMeal-018](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0/_edit#test-case-id-aa-deletemeal-018) : Passed, bug were not reproducible..
