### ISSUE TITLE
Search Meal Plan doesn't work with upper case

### ISSUE THREAD

**Issue by SadPlum** [CivicTechFredericton/mealplanner#438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari]
 - Platform [e.g. IDE, docker-compose, QA site]

**Additional context**

**Comment by thetinshusasi** [comment]
please share the a video or steps to reproduce this issue
