### ISSUE TITLE
Unit Conversion Table For Products [FEATURE] 

### ISSUE THREAD

**Issue by arhtivap** [CivicTechFredericton/mealplanner#441]
**Is your feature request related to a problem? Please describe.**
Yes. The products were displayed in various units such as grams(g), kilograms(kg), pounds(lb), millilitres (mL), litre(L), ounce(oz), etc. It is very difficult to convert these units while extracting the price for the recipes from the measures table.

**Describe the solution you'd like**
I have implemented the feature to convert grams(g), and pounds(lb) to kilograms(kg). And keeping the kilograms(kg) as is. And  millilitres (mL), ounce(oz) to litre(L). And keeping the litre(L) as is.

**Comment by shanthisa** [comment]
It has to be a table that is created in the database which has the unit conversion. While the PR addresses this in the admin UI, it doesn't satisfy the requirement for the shopping list or even the meal view. I would suggest to close this PR and I will write a ticket for the feature requirement.
