### ISSUE TITLE
Duplicate Products found in recipes_seed.sql file [BUG] 

### ISSUE THREAD

**Issue by arhtivap** [CivicTechFredericton/mealplanner#448]
**Describe the bug**
If the same product is used as measures in different recipes only one product needs to be created. 

**To Reproduce**
Removed the duplicate products from the recipes_seed.sql file and checked if the duplicates are removed by running the script. It worked perfectly.

**Expected behavior**
Now the recipes_seed.sql file doesn't have any duplicates.

**Comment by rorybray** [comment]
closing as complete, has been merged to develop.
