### ISSUE TITLE
Duplicate Products found in seed.sql file [BUG] 

### ISSUE THREAD

**Issue by arhtivap** [CivicTechFredericton/mealplanner#451]
Describe the bug
If the same product is used as measures in different recipes only one product needs to be created.

To Reproduce
Steps to reproduce the behaviour:
Removed the duplicate products from the seed.sql file and checked if the duplicates are removed by running the script. It worked perfectly.

Expected behaviour
Now the seed.sql file doesn't have any duplicates.

**Comment by rorybray** [comment]
Closing as complete. Has been merged to develop.
