### ISSUE TITLE
Favorite feature for meal

### ISSUE THREAD

**Issue by RiyaKapuria** [CivicTechFredericton/mealplanner#455]
For the meal, the users should be able to mark it as Favorite when they log in.
Also, there should be a sorting feature with the Favorite category.

**Comment by shanthisa** [comment]
Please find a mockup on what the UI should look like for Favourites and the favourites table structure. When the heart symbol is clicked, first check whether there is an entry for the corresponding meal and the current logged in user. If not, insert the record. In the UI when the meal is a favourite it should look green. When the heart symbol is clicked, if the entry is already in the table, then it should be deleted. In the UI, when the meal is not a favourite, it should look transparent.
Also please note, the filter should happen only for one at at time, either Search by name, or Favourites or Tags.
Filter by Tags should be for an 'and' relation. Eg: Meals that are with both nut-free and Veg tags should appear in search. Also if there are additional tags, still they appear in the list. Filter by tags is a part of a different ticket. This ticket only encompasses Favourites. Filter by tag is explained here only to get the overall picture.
![PXL_20240207_153026062](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/b4815dcf-7d6b-4a02-92c2-ece66eb6b230)
![PXL_20240207_153030327](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/8fc08dbc-23c5-4a0f-a47a-c4f820da510d)

![PXL_20240207_153022002](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/6616fb76-1907-46f9-82b6-ea001d2af244)

**Comment by shanthisa** [comment]
#516 needs to be completed before this. I am working on it.

**Comment by shanthisa** [comment]
As per the changes in #516, when a route is presented with a slug, depending on the user slug, the favorites is displayed.
This permission is given for admin and meal designer. 
This has been clearly described in the PR
https://github.com/CivicTechFredericton/mealplanner/pull/524
Your UI is not satisfying the backend of this. You are only doing the current user.  Please read the scope of 524 PR description and accordingly modify the frontend to support it.

As an admin or meal designer I should be able to view the favorite meals of any user. 
As a app_user I will be able to view only my current favorite meal.

**Comment by shanthisa** [comment]
While writing QA for this please ensure you read the description of the pull requests. As the pull requests description describes the functionality clearly more than the ticket description

**Comment by folaj034** [comment]
QA id done.
 Test case ID: MP-Favoritefeatureformeal-085 : Passed
Test case Test case ID: MP-SortingfeaturewithFavoritecategoryformeals-086 : Passed

**Comment by folaj034** [comment]
QA is done.
[MP-Favoritefeatureformeal-085] : Passed
[MP-SortingfeaturewithFavoritecategoryformeals-086]  : Passed

**Comment by folaj034** [comment]
QA is done
Test case  | [MP-Favoritefeatureformeal-085](#085) |  : Passed

**Comment by folaj034** [comment]
QA is done
Test case  [MP-Favoritefeatureformeal-085](#085)   : passed

**Comment by folaj034** [comment]
[AA-UnitDisplayedNextToQuantityInProductMatch-090](#090)

**Comment by folaj034** [comment]
MP-CivictechLogOnMealPlan-084

**Comment by folaj034** [comment]
[AA-UnitDisplayedNextToQuantityInProductMatch-090](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#090)

**Comment by folaj034** [comment]
QA is done
Test case [MP-Favoritefeatureformeal-085](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#085) : Passed
