### ISSUE TITLE
[FEATURE] No search bar on Admin App (Meals)

### ISSUE THREAD

**Issue by valentim82** [CivicTechFredericton/mealplanner#457]
**Is your feature request related to a problem? Please describe.**
There needs to have a search bar on Admin App Meal List.

**Describe the solution you'd like**
As an admin or user, I would like to have a search bar on the navbar of Admin App, showing quickly a specific meal.

**Describe alternatives you've considered**
...

**Additional context**
![image](https://github.com/CivicTechFredericton/mealplanner/assets/34504307/85de40b0-4510-46ea-82ab-4288ad79c632)

**Comment by shanthisa** [comment]
@ala-sk98 - Can you please test this?

**Comment by ala-sk98** [comment]
QA done.
Test case [AA-SearchBarMeals-028](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-SearchBarMeals-028) : Passed
