### ISSUE TITLE
[BUG] trash can and shopping cart icons not turning green when hovering the mouse over

### ISSUE THREAD

**Issue by okayyjen** [CivicTechFredericton/mealplanner#459]
**Describe the bug**

in the meal plans page, the trash can and shopping cart icons are not turning green when hovering the mouse over the icons. 

**To Reproduce**
1. Go to '/mealplans'
2. Hover mouse over the trash can and shopping cart buttons/icons
4. The buttons/icons are not turning green

**Expected behavior**
The trash can and shopping cart icons should turn green when the mouse is hovering over them.

**Screenshots**

**Test Environment (please complete the following information):**
 - any browser [Chrome, Firefox]

**Comment by shanthisa** [comment]
I have requested changes. Please check the PR

**Comment by ala-sk98** [comment]
QA done.
Test case[MP-IconHoverColor-024](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-iconhovercolor-024) : Passed

**Comment by ala-sk98** [comment]
@shanthisa According to the test case, for the UI perspective,  can I create an issue to change the color of the duplicate icon, which is beside the trash and cart icon?



![Image](https://github.com/CivicTechFredericton/mealplanner/assets/59191427/f64b7ca8-263e-4d8c-9be3-1c2f3c70331e)

**Comment by shanthisa** [comment]
@ala-sk98 - I think it can be part of the same ticket
@okayyjen - Can you please set the color for duplicate icon too?

**Comment by okayyjen** [comment]
@shanthisa yes, I can do that

**Comment by olamakhlouf** [comment]
QA done.
Test case[MP-IconHoverColor-024](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-iconhovercolor-024) : Passed

Tested  the duplicate icon

**Comment by shanthisa** [comment]
Looks good. Closing this issue.
