### ISSUE TITLE
[FEATURE] no confirmation dialogue is shown when deleting a meal plan

### ISSUE THREAD

**Issue by okayyjen** [CivicTechFredericton/mealplanner#460]
**Describe the bug**
In the meal plans page, when the user deletes the trash icon to delete a meal plan, the user should be able to see a confirmation dialogue, so that the user can confirm whether or not they actually want to delete the specified meal plan.

**To Reproduce**
1. Go to '/mealplans'
2. Click on the trash can button
3. No confirmation dialogue shown

**Expected behavior**
on the meal plans page, when the user clicks on the trash button to delete a mealplan, the user should be getting feedback on whether the delete was successful or not.

**Test Environment (please complete the following information):**
 - Browser and version [chrome, Firefox]

**Comment by shanthisa** [comment]
I had requested two small changes. Please look into it.

**Comment by shanthisa** [comment]
Reviewed and merged. Off to QA.

**Comment by ala-sk98** [comment]
QA done.
Test case[MP-ConfirmDelete-025](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-confirmdelete-025)  : Passed

**Comment by okayyjen** [comment]
LGTM
