### ISSUE TITLE
[BUG] migrations need to execute without errors

### ISSUE THREAD

**Issue by rorybray** [CivicTechFredericton/mealplanner#467]
**Describe the bug**
The 004-269-index-category-days.sql migration script throws errors when it runs on an existing DB. It should be re-runnable without errors.

**To Reproduce**
1. docker-compose up --build
2. See error

**Expected behavior**
Error-free sql output during compose-up

**Comment by shanthisa** [comment]
@ala-sk98 - can you please test this?

**Comment by ala-sk98** [comment]
> @ala-sk98 - can you please test this?

Sure. Will test it.

**Comment by shanthisa** [comment]
This is no more applicable because db_migrations has come in place.
