### ISSUE TITLE
[Meal] - Print meal should have civic tech logo and name

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#469]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 As a user/admin/meal designer, I would like to see the Civic Tech logo and name in the printout of the recipe (meal) so that they know who has created them :-)

**Comment by shanthisa** [comment]
@ala-sk98 - As Pujitha is unavailable and this is a very simple fix, I was wondering whether you can take this up. If yes, please comment on this ticket.

**Comment by ala-sk98** [comment]
Hi Shanthi, thanks for sharing. I'll work on this issue.

**Comment by olamakhlouf** [comment]
Hi @shanthisa  the civic tech logo is there but in the separate page. Also, there is no ingredients displayed
![Screenshot from 2024-04-16 13-33-50](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/88adade5-bb82-49e6-b815-c9a57e61cce4)
![Screenshot from 2024-04-16 13-33-58](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/6b74b7ff-82b2-45cc-b56d-7013c46142d9)

**Comment by shanthisa** [comment]
This should be fixed as part of this ticket. The CivicTech logo and the message should be displayed in the footer of every page.

**Comment by olamakhlouf** [comment]
QA Done
Test Case [MP-DisplayCivicTechLogo-074](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-DisplayCivicTechLogo-074): passed
