### ISSUE TITLE
E7.05 Add/update/archive item in Catalog of Meals

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#47]
As Meal Designer, I should be able to add/update/archive an item in the catalog of meals, so I can use the meal when I make the plan for clients.

Acceptance Criteria:

- "Meal" can be selected from Catalog
       - "Add a meal" button
       - Pressing the button will open the "Meal creation page" 
- Image /video can be added. Images must be at least 500*500 pixels and in JPEG, GIF, or PNG format
- Name, description/instruction, and other details (Eg. label: gluten-free) for meals can be added and saved
- Newly added meals are searchable and editable

Consideration:
- Hide function to hide unavailable meal
- Pop-up message to notify successful "Add" or "Update"

**Comment by Joycelyn2015** [comment]
Features mentioned are already implemented. Closing this now.
