### ISSUE TITLE
[BUG] favourites icon doesnt turn red on mouse hover

### ISSUE THREAD

**Issue by okayyjen** [CivicTechFredericton/mealplanner#476]
**Describe the bug**
Favourites/heart icon doesn't turn red on mouse hover

**To Reproduce**
1. Go to '/mealplans'
2. hover mouse over favourites/heart icon
3. icon doesn't turn red

**Expected behavior**
The favourites/heart icon should turn red on mouse hover

**Screenshots**

**Test Environment (please complete the following information):**
 - any browser (chrome, firefox)

**Comment by shanthisa** [comment]
Review was given in the PR. Please check and do the required changes

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-FavouritesHover-026](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-FavouritesHover-026) : Passed

**Comment by okayyjen** [comment]
LGTM
