### ISSUE TITLE
E7.06 Search item in Catalog of Meals

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#48]
As Meal Designer, I should be able to search for an item in the catalog of meals, so I can update the item or use the item in my meal plan.

Acceptance Criteria:

- Item can be searched by Name or ID
- Error message if no match
- The search results can be viewed in a list
- The search results can be selected for viewing in details or updating

-Consideration:
- Both full and partial match should be attempted
- For a partial match, at least 3 characters should match
- Add "Filter" to search and results (Eg. filter the results by choosing specific sections)
- Add "Sort" for results (Eg. Relevance, date)
- Filter can be reset at once or separately

**Comment by shanthisa** [comment]
@RLCASTRO - Please look at this issue and see whether it satisfies and bring it to our daily for any clarifications.

**Comment by shanthisa** [comment]
We have implemented search meal with name. As of now that is sufficient. In case client comes back with requirements we can create new user stories. Closing this as of now.
