### ISSUE TITLE
[BUG] When creating measure, not all products displayed in Admin app

### ISSUE THREAD

**Issue by okayyjen** [CivicTechFredericton/mealplanner#482]
**Describe the bug**
On the Admin app, when the user goes to create a measure, one of the required fields to fill out is to specify the product from the drop down. However, not all available product is displayed, preventing the user from creating a measure for their desired product.

**To Reproduce**
1. Go to 'measures/create'
2. Click on 'product'
3. See that not all products are listed

**Expected behavior**
when the user goes to create a measure, and click on the 'product' drop down, the user should be able to see all the available products so that they can create measure for specific product.

**Test Environment (please complete the following information):**
 - Any browser [e.g. chrome, safari]

**Comment by shanthisa** [comment]
Reviewed and Merged.
@ala-sk98 - Please test this.

**Comment by ala-sk98** [comment]
> Reviewed and Merged. @ala-sk98 - Please test this.

Sure, will work on it.

**Comment by ala-sk98** [comment]
QA is Done for [AA-ProductDropdownDisplay-022](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-aa-productdropdowndisplay-022): Passed

**Comment by okayyjen** [comment]
QA testing passed. closing issue
