### ISSUE TITLE
[BUG] Updating the Quantity and Unit for the product Lettuce.

### ISSUE THREAD

**Issue by arhtivap** [CivicTechFredericton/mealplanner#489]
**Describe the bug**
Lettuce is listed as a 3 count in the products table. It will be easy to extract the price for the recipe if it is listed as 1 each. 

**To Reproduce**
Changed the quantity and unit for Lettuce in the recipes_seed.sql file as 1 each respectively. Updated the cost and product link as well.

**Expected behaviour**
Now Lettuce will be listed as 1 ea in the products table.

**Comment by shanthisa** [comment]
I don't see a pull request for this. I will remove Pavitra as she is currently not available. Anyone can look into this issue.

**Comment by introkun** [comment]
I'd like to have a look, but not able to assign it to myself

**Comment by RLCASTRO** [comment]
I believe I assigned to you @introkun. Good luck

**Comment by introkun** [comment]
**In-Progress**

**Comment by shanthisa** [comment]
Test case:
Deleting the existing database and the seed sql should run smoothly and meals and measures should be visible in the meal-planner UI
Note: A future change would come where we would not be using this seed sql. But for now this fix is good to go.

**Comment by shanthisa** [comment]
Anyone who would like to test in v2 can test it and then we can close this issue.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-ProductQuantityUpdate-027](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-ProductQuantityUpdate-027) : Obsolete
