### ISSUE TITLE
[FEATURE] No search bar on Admin App (Products)

### ISSUE THREAD

**Issue by RLCASTRO** [CivicTechFredericton/mealplanner#505]
**Is your feature request related to a problem? Please describe.**
As a user of the admin-ui, I need a search bar to facilitate finding existent products.

**Describe the solution you'd like**
A better way to find a specific product by its name, code, UPC or tags

**Additional context**
Something similar to the image below that shows the search bar for the Meals resource.
![image](https://github.com/CivicTechFredericton/mealplanner/assets/37277959/529bf4f0-aa4c-461a-a77c-777b00dc6e6e)

**Comment by shanthisa** [comment]
@ala-sk98 - I assume you tested this and had some QA remarks. Please mention the remarks in this ticket.

**Comment by ala-sk98** [comment]
QA done.
Test case[AA-SearchBarProducts-023](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-SearchBarProducts-023) : Failed;  Issue #593 created to address it.

**Comment by shanthisa** [comment]
Addressed to #593
