### ISSUE TITLE
E6.02 Update an item in catalogue of units

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#51]
As the administrator, I update an item in catalogue of units, So
>>>administrator
>>>meal designer 
can use actual data about a unit 

>>>when he create or update an item of catalogue of meals or item of catalogue of products

**Comment by Joycelyn2015** [comment]
Duplicate of issue #50: E7.02 Create/Update/Archive item in Catalog of Units
