### ISSUE TITLE
[FEATURE] My favourite meal

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#516]
**Is your feature request related to a problem? Please describe.**
The favourite meals of the current logged-in user are shown.

**Describe the solution you'd like**
As a user/admin/designer, I would like to have an option to view my favourite meals so that I can easily choose from them.

**Additional context**
When the current user queries for the favourite meals, the default Postgraphile will pass all the favourite meals, and we need to check in the frontend whether the favourite meal matches the current user and accordingly display. This has a security leak of the user being able to query through the Development console the favourite meals of other users. So we need to write a RLS (row level security) in the backend to query only the current user's favourite meal.

**Comment by ala-sk98** [comment]
QA is Done. 
Test case [MP-MyFavouriteMeal-039](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-MyFavouriteMeal-039): Passed

**Comment by shanthisa** [comment]
There is no information on where to find the My favorite Meals. Moreover there is no test data. Please ensure there are clear navigation steps and test data in a test case.

**Comment by olamakhlouf** [comment]
@shanthisa 
QA is Done.
Test case [MP-MyFavouriteMeal-039](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-MyFavouriteMeal-039): updated and passed
