### ISSUE TITLE
[FEATURE] Filter by tag for meals page

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#517]
**Is your feature request related to a problem? Please describe.**
Provide three options as radio buttons. Search by name, filter by tag, filter by favourites

**Describe the solution you'd like**
As a [user/admin/designer] I would like to filter the meals by tags.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-FilterByTagMeals-021](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-filterbytagmeals-021) : Passed
