### ISSUE TITLE
[FEATURE] Insert a tooltip for name and description on the meal plan creation page

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#518]
**Is your feature request related to a problem? Please describe.**
Currently the mealplan names can be done arbitrarily and in future it maybe difficult to search based on name. So if we suggest a convention as a suggestion, it will guide the meal designer or the user to create the same.
**Describe the solution you'd like**
As a [admin/designer], I would like to have a tooltip for the name of mealplan during creation
My suggestion for name tooltip is
'Suggestion: Client # Week #'
As a user, the tooltip can show as
'Suggestion: Family member name Week #'
As a [user/admin/designer], I would like to have a tooltip for description of mealplan during creation
My suggestion for description tooltip is 
'Suggestion: Notes on the discussion with client about their requirements, your suggestions.'

**Comment by shanthisa** [comment]
@ala-sk98 - This is a very easy issue. Would you like to take this up?

**Comment by ala-sk98** [comment]
> @ala-sk98 - This is a very easy issue. Would you like to take this up?

Sure, Shanthi. I'll work on it.

**Comment by RLCASTRO** [comment]
Hi @shanthisa, I believe you assigned this to me by accident.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-InsertTooltip-029](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-InsertTooltip-029) : Passed

**Comment by RLCASTRO** [comment]
Test case reviewed, LGTM. @shanthisa can you close this issue please?
