### ISSUE TITLE
[FEATURE] Filter by tags for meal plan

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#522]
**Is your feature request related to a problem? Please describe.**
When the mealplan is created or deleted, the tags should be automatically listed on the Filter by tags view

**Describe the solution you'd like**
As a [user/admin/designer] I would like to view the unique list of meal plan tags displayed for the list of meal plans available so that I can filter by tags.

**Describe alternatives you've considered**
There was a ticket for meal plan tag #437, which was implemented to create 3 options. The problem with that issue was we need to refresh the whole page or go to a different option for all tags to be displayed correctly after a meal plan creation or deletion.

**Additional context**
This required quite new code to handle 'state' in the relay. Also, I introduced graphql 'fragment' to manage the state. Since this was a significant rewrite of code, I handled it as a separate issue.

**Comment by shanthisa** [comment]
@ala-sk98 - Can you please QA this? Thanks.

**Comment by ala-sk98** [comment]
QA done.
Test case [MP-FilterByTags-015](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0/_edit#test-case-id-mp-filterbytags-015): Passed.

**Comment by shanthisa** [comment]
Test case ID updated [MP-filterbytags-015](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-mp-filterbytags-015)

**Comment by ala-sk98** [comment]
QA done.
Test case[MP-FilterByTags-030](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-FilterByTags-030) : Passed

**Comment by shanthisa** [comment]
@ala-sk98 Please provide test data and clear navigation steps

**Comment by olamakhlouf** [comment]
QA Updated.
Test case[MP-FilterByTags-030](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-FilterByTags-030) : Passed

**Comment by olamakhlouf** [comment]
@shanthisa  updated the test case
