### ISSUE TITLE
[FEATURE] Updated the table meal to have prep time, cook time, portions

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#537]
**Is your feature request related to a problem? Please describe.**
Earlier there was cooking_duration and servings as the column. Changed the column names of meal to prep time, cook time, portions as per the format of recipes shared by Greener village.
**Describe the solution you'd like**
 As a [user/admin/desinger] I would like to have the recipes show the preparation time, cook time and portions.

**Additional context**
This will take care of the sql database part. Frontend will be part of the ticket #529.

**Comment by ala-sk98** [comment]
QA is done.
Test case  [MP-UpdateMealTable-040](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-UpdateMealTable-040): Passed

**Comment by shanthisa** [comment]
LGTM 👍
