### ISSUE TITLE
 E7.01 Add/Update/Archive item in Catalog of Products

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#54]
As Meal Designer, I want to add/update/archive items in the catalog products with price.
This will be used in creating or updating items in the catalog of meals.

There are 2 types of products:
-Generic food categories (e.g. carrots, potatoes, tomatoes)
-Food items sold in Supermarkets (e.g. Walmart)

Acceptance Criteria:
Scenario 1 Generic food 
- "Generic food categories" can be selected from the catalog
- "Add" button
- Pressing the button will open the "product adding form"
- Edit/update an existing product
- The price can be viewed with the product
- The price is for a single unit and in currency format. (Eg, 1 each broccoli  $3.00 or 1 bag of carrots  $3.00)
- Name and price can be added and saved
- Quantity of products can be viewed and changed

Scenario 2 Supermarket food
- "Supermarket food categories" can be selected from the catalog
- "Add" button
- Pressing the button will open the "product adding form"
- Edit/update an existing product
- The price can be viewed with the product
- The price is for a single unit and in currency format. (Eg, 1 can chicken broth  $3.00)
- Name and price can be added and saved
- Quantity of products can be viewed and changed

Consideration:
- Image can be added. Images must be at least 500*500 pixels and in JPEG, GIF, or PNG format
- Pop-up message to notify successful "Add" or "Update"
- Order date and expiration date added with the product

**Comment by Joycelyn2015** [comment]
For review and refinement of requirements.
