### ISSUE TITLE
[FEATURE] When a specific meal is clicked it needs to be viewable even without logging in.

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#560]
**Is your feature request related to a problem? Please describe.**
The meals page is accessible without logging in. However the individual meal page is not visible without logging in.

**Describe the solution you'd like**
As an anonymous person, I would like to view the meals of Greener village without having to login so that I can view the meal recipes.

**Comment by ala-sk98** [comment]
QA is Done. 
Test case [MP-ViewMealWithoutLogin-063](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-ViewMealWithoutLogin-063): Done

**Comment by ala-sk98** [comment]
@okayyjen Please review QA and close.

**Comment by okayyjen** [comment]
LGTM @shanthisa can you close this please?

**Comment by okayyjen** [comment]
@ala-sk98 were you able to see the details of a meal without needing to login? sorry I can't tell from the screenshot.

**Comment by shanthisa** [comment]
@okayyjen  The user and logout button would appear if there is a user logged in. Since the screenshot does not have any, it is safe to assume that. In future we will have a login link for clearer visuals.

**Comment by shanthisa** [comment]
@ala-sk98  You need to say how do you 'Navigate to the Meals page of Greener Village without logging in'. Like 'Go to http://goodmealplan.com/meals'

**Comment by olamakhlouf** [comment]
QA is Updated.
Test case [MP-ViewMealWithoutLogin-063](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-ViewMealWithoutLogin-063): Passed
