### ISSUE TITLE
[FEATURE] Adding Image and Video as embedded rather than a url or text

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#566]
**Is your feature request related to a problem? Please describe.**
Currently the image and video url of a meal is shown as text or url

**Describe the solution you'd like**
As a user it will be easier for me to decipher what image or video it is if it shows as a thumbnail video and an image for each recipe

**Describe alternatives you've considered**
The other alternative was a url

**Additional context**
Increases UX.

**Comment by ala-sk98** [comment]
QA is Done.
Test case [AA-ImageVideoEmbedding-036](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-ImageVideoEmbedding-036) : Passed

**Comment by shanthisa** [comment]
@ala-sk98  - Please provide navigation steps and test data

**Comment by olamakhlouf** [comment]
QA is Done. 
Test case [AA-ImageVideoEmbedding-036](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-ImageVideoEmbedding-036) : require revision

**Comment by olamakhlouf** [comment]
QA is Done.
Test case [AA-ImageVideoEmbedding-036](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-ImageVideoEmbedding-036) : Passed
