### ISSUE TITLE
[FEATURE] Delete measure table

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#568]
**Is your feature request related to a problem? Please describe.**
Delete measure table as match is going to come up

**Describe the solution you'd like**
This measure table provided a 1-1 relationship between ingredient and product. Going to make it many-many with match. 

**Describe alternatives you've considered**
Yes. Match

**Additional context**
Additional context will be in the match issue

**Comment by ala-sk98** [comment]
QA done.
Test case  [MP-DeleteMeasureTable-033](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-DeleteMeasureTable-033)  : Passed in V1, According to the issue #603 Shopping list under the construction.

**Comment by shanthisa** [comment]
@ala-sk98  This test case is wrong. You can't delete the measure table from the admin UI. The test case should be 
Go to admin UI.
Check for a section 'Measure' - Should not be present
Check for Ingredients under Meals - Should be present

**Comment by cybernetrho** [comment]
@RLCASTRO @olamakhlouf 
QA done.
Test case [AA-DeleteMeasureTable-102](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#102)  : passed
