### ISSUE TITLE
[FEATURE] Match multiple products to an ingredient

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#570]
**Is your feature request related to a problem? Please describe.**
Currently the measure table maps only one product to one ingredient. The problem is we can't decide which is the right product to be mapped as there are multiple options and the chef or the meal designer or the user will need to be able to decide the best option.

**Describe the solution you'd like**
As an admin/meal designer, I can choose multiple products as match for an ingredient and recommend one as the best option.

**Describe alternatives you've considered**
The earlier option which was measure was constraining the choices.

**Additional context**
This is required to be viewed in the shopping list.

**Comment by olamakhlouf** [comment]
QA is Done.
Test case [MP-MatchProductsToIngredient-072](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-MatchProductsToIngredient-072): Passed

**Comment by shanthisa** [comment]
@olamakhlouf  This test case looks good. It would be better to add the step of 'best' (Select the best product..) also and to verify that the **best** is also appearing in the shopping list page.

**Comment by olamakhlouf** [comment]
@shanthisa  done.
