### ISSUE TITLE
[BUG] Numerous meal tags should be aligned properly

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#580]
**Describe the bug**
When there are many meal tags they just horizontally scroll to that length and it looks ugly

**To Reproduce**
1. Go to 'Meals'
2. Click on 'Filter by tag'
3. Scroll right and see so many tags

**Expected behavior**
When there are many tags, they should be aligned in multiple lines to the given width of the main page.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/CivicTechFredericton/mealplanner/assets/57197486/fec706f9-1eda-4553-b47e-6e50be1016f8">

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] chrome
 - Platform [e.g. IDE, docker-compose, QA site] docker-compose

**Comment by olamakhlouf** [comment]
QA is Done
test case : [MP-TagsAlignedCorrectry-076](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#076) Passed

**Comment by shanthisa** [comment]
@olamakhlouf  - Spelling mistake 'Correctry' should be correctly. Also please start all sentences with Capital letters. Like 'verify' and 'tags' should start with capitals as 'Verify' and 'Tags'.

**Comment by olamakhlouf** [comment]
Thanks @shanthisa. I fixed those now.

**Comment by shanthisa** [comment]
Thanks @olamakhlouf  Closing this issue
