### ISSUE TITLE
[BUG] In admin UI, tags and product keywords could not have spaces

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#584]
**Describe the bug**
A product keyword or a tag cannot have space in the current implementation. 
**To Reproduce**
1. Go to 'mealplanner admin ui'
2. Click on Products -> select a product
3. Scroll down to Product Keywords
5. Enter 'egg noodles' as the product keyword. It will not allow you to enter the space between 'egg' and 'noodles'

**Expected behavior**
Should be possible to give words such as 'feta cheese' and 'egg noodles', 'large eggs'.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] docker-compose

**Comment by shanthisa** [comment]
Merged. Ready to QA

**Comment by ala-sk98** [comment]
QA is completed.
Test case [AA-ProductKeywordsSpaces-034](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-ProductKeywordsSpaces-034): Passed Successfully

**Comment by shanthisa** [comment]
Pre-requisite should be a test case ID
Exact steps of navigation should be mentioned. 
Include Test data in the test case.

**Comment by ala-sk98** [comment]
@shanthisa test case updated with your comments

**Comment by shanthisa** [comment]
@ala-sk98  Exact steps of navigation is not mentioned. Also each scenario should be seperate test case. Imagine you are automating this test case. Should the automation script be creating or editing the product? There will be two automated tests written for create and edit product isn't it? That's how you write test cases too.

**Comment by olamakhlouf** [comment]
@shanthisa  QA is done
Updated the test case with data and navigation steps
sepereted test cases
[AA-TagSpaces-034](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#083): passed
[AA-ProductKeywordsSpaces-034](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#034): passed
