### ISSUE TITLE
9 Setup of Environment

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#59]
AWS – Engine, DB
UI – React

**Comment by Joycelyn2015** [comment]
Meal Planner ER Diagram can be found here:

https://drive.google.com/drive/folders/19r02G1G86oMOJ8vs8fUNm8ZJ-YtOqNkV

1. Download this file to you local drive.
2. Go to draw.io.  Select Open Existing Diagram and open the file you just downloaded.

**Comment by rorybray** [comment]
All related issues are now closed.
