### ISSUE TITLE
[FEATURE] Meals has a show page and a show button in admin UI and edit redirects to Show instead of meals list

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#590]
**Is your feature request related to a problem? Please describe.**
While showing a demo of meal edit, I realized that after saving going back to the meals page, means, I need to do a search everytime I need to view the meal. That would not be a good user experience. 
**Describe the solution you'd like**
So I created a show page that shows the meal data. On save after edit, it redirects to the meal show page. Additionally also added a show button.

**Describe alternatives you've considered**
Going back to meals list page

**Comment by ala-sk98** [comment]
QA is Done.
Test Case [AA-MealsShowPage-038](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-MealsShowPage-038) : Passed

**Comment by shanthisa** [comment]
Test case looks good.
