### ISSUE TITLE
[BUG] Search Product is not working and all products are not showing in the list

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#593]
**Describe the bug**
All products are not listed in the table of admin UI

Example: "2940" which is "| Great Value All Beef Meat Lasagna, 907 g |         |  7.97 |      907 | g    | f           | 6000197484956 | https://www.walmart.ca/en/ip/Great-Value-All-Beef-Meat-Lasagna/6000197484957 |      | 2024-03-17 15:41:37.645393 | 2024-03-17 15:41:37.645393 | {noodles}        | https://i5.walmartimages.com/asr/d0cba543-dd15-434e-97b5-e2491359bb9b.75fb11d7963f6d1552556c7c8ec29f8e.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff" 
existing in the database
When you search for a particular product, it does not show the product despite the product being present. These problems could be related.

**To Reproduce**
1. Go to psql
2. Search for select * from app.product where id=2940;
3. You will see '2940 | Great Value All Beef Meat Lasagna, 907 g'
4. Go to admin ui
5. Search for the product 'Lasagna'. There are no search results

**Expected behavior**
All records in the database should appear in admin UI and the search should yield the results of the searched phrase if present.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by ala-sk98** [comment]
QA is Done.

Test case [AA-SearchProductBug-062](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-SearchProductBug-062): Passed

**Comment by ala-sk98** [comment]
@RLCASTRO Please review QA and close.

**Comment by RLCASTRO** [comment]
Test case reviewed. LGTM 👍
