### ISSUE TITLE
[BUG] When we try to create an ingredient we get an error

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#595]
**Describe the bug**
When we try to create an ingredient we get this error.

**To Reproduce**
1. In admin UI, Go to a meal
2. Click on Ingredients
3. Click on Create
4. Fill up the values
5. See error

**Expected behavior**
Should be able to add successfully.

**Screenshots**

![image (4)](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/cc60ce0b-da22-44f4-8a01-14e88ae0cb28)

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by ala-sk98** [comment]
QA is completed. 
Test case [AA-IngredientCreationError-035](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-IngredientCreationError-035) :Passed

**Comment by RLCASTRO** [comment]
Hi @ala-sk98.
Following the same steps described in your tests will successfully create the ingredient. But there are errors when you don't provide the minimum information in the form. The image below exemplifies this:

In the ingredient creation form:
1. provide the ingredient name field only
2. The save button turned blue
3. Click in save
4. An error is returned

I'll add the validation for the necessary fields and request a review again.

![image](https://github.com/CivicTechFredericton/mealplanner/assets/37277959/322bfecd-bc57-427a-9729-99292b32e4b4)

**Comment by ala-sk98** [comment]
@RLCASTRO, the QA is updated with the error. Test case status of [AA-IngredientCreationError-035](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-IngredientCreationError-035) is updated.

**Comment by RLCASTRO** [comment]
Test case reviewed. LGTM 👍
