### ISSUE TITLE
[DOCS] Populating Sample Data

### ISSUE THREAD

**Issue by RLCASTRO** [CivicTechFredericton/mealplanner#598]
**Target Document**
- which document, by name
README.md

- location of document [wiki, google drive, etc]
mealplanner/readme.md

**Describe the issue or error**
To populate the database with sample data we need to create a new .env file with a DB_URL environment variable declared. This needs to be added to the readme.md

**Suggested edits**
Add a new section on the mealplanner/data/README.md  or in the main readme.md

**Comment by shanthisa** [comment]
There should be a .env file under mealplanner\data folder with the values
DB_URL="postgresql://postgres:dbpassword@servername:port/postgres

If you are using .envrc use
export DB_URL="postgresql://postgres:dbpassword@servername:port/postgres
In command prompt give direnv allow

export DB_URL="postgresql://postgres:databasepassword@127.0.0.1:5433/postgres"

**Comment by shanthisa** [comment]
Reviewed the documentation changes with the team.
Set port to 2000 for admin UI
