### ISSUE TITLE
[BUG] Templates should be displayed with all meal plans

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#602]
**Describe the bug**
Currently Templates are visible only when filter is selected for Template. Which means it is invisible by default. The list should contain all meal plans including templates.

**To Reproduce**
1. Go to 'Meal plan'.
2. Click on 'Create Template'
3. View the list to see the template
4. No template is seen

**Expected behavior**
Templates should appear along with meals.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Additional context**
Templates are available on filter by Template.

**Comment by ala-sk98** [comment]
QA is Done. 
Test case [MP-DisplayTemplates-064](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-DisplayTemplates-064): Passed

**Comment by ala-sk98** [comment]
@priyaguntupalli5 It's been here for a while. can you review the test case?

**Comment by priyaguntupalli5** [comment]
Reviewed and moved. Thanks for letting me know!
