### ISSUE TITLE
[FEATURE] Shopping List

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#603]
**Is your feature request related to a problem? Please describe.**
Shopping List should show all the ingredients, meal it belongs to and the product suggestions. Estimated total price is not required.
**Describe the solution you'd like**
As an admin/meal designer/user I should be able to view the shopping list of all the ingredient products for my selected meal plan.

**Describe alternatives you've considered**
As of now under construction. Earlier implemented with measure showed exhorbitant prices for estimate prices.

**Additional context**
Change in table structure from measure to ingredient and match tables. #570

A draft mockup of how it should look like

![Image](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/05df1380-e83a-4da2-85e9-9f53292222cb)

**Comment by shanthisa** [comment]
Add a price to the product as 
Product Name - $<price>

Eg: 
Great Value Macaroni, 400g - $5

**Comment by shanthisa** [comment]
Add a disclaimer note: in italics just above the table
**_Disclaimer_**: _The suggested products are intended to be used as reference for informational purposes only. This is not a recommendation of where to buy. Clients need to research and verify which is suitable to their needs independently. Prices are indicative as per the data procured in March 2024. The prices may vary subject to the time of purchase, store and mode of purchase._

**Comment by shanthisa** [comment]
Substitute of Green Pepper is Red Pepper. In such a case we need to show in the ingredient list as follows: 

Green Pepper ....

Red Pepper
_Substitutes: Green Pepper_

**Comment by shanthisa** [comment]
@okayyjen Please address the subsititute quantity and unit as part of #637 I am moving this ticket to QA

**Comment by olamakhlouf** [comment]
QA is done.
Test case [MP-ShoppingList-101](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#101): Passed.
