### ISSUE TITLE
[FEATURE] Ingredients needs to visible in Meal page

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#609]
**Is your feature request related to a problem? Please describe.**
Ingredients need to be visible for each meal in the mealplanner UI
**Describe the solution you'd like**
 Meal page should have the ingredients listed as per the meal recipe along with quantity and unit.

**Describe alternatives you've considered** && **Additional context**
We had measures and product only earlier. The product name was same as ingredient name earlier. Now  we want to distinguish between ingredient and product. Hence we created an ingredient table and match table. So Ingredient needs to queried from the respective table  for the respective meal.

**Comment by shanthisa** [comment]
Thanks for sharing the screenshot. This showed an important field we need to show. Need to show which is the substitute ingredient and which is the substitute it is for and what reason.
Eg:
The original recipe doc says Kosher or Regular salt 1 tsp
So we can show this as follows in our UI:

Kosher Salt 1 tsp
-------------------
Regular Salt 1 tsp
Substitute for: Kosher Salt 
Reason: not specified
--------------------

**Comment by shanthisa** [comment]
@RLCASTRO - Requested to use them for colours. Please check PR comment and create a new PR with the same ticket.

**Comment by ala-sk98** [comment]
QA is done
Test case  [MP-IngredientsTable-068](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-IngredientsTable-068): passed

**Comment by RLCASTRO** [comment]
Test case reviewed. LGTM 👍 Please close the issue when you can @shanthisa.
