### ISSUE TITLE
[BUG] Meal name should appear in the ingredient page of admin UI

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#621]
**Describe the bug**
Meal name should appear in the ingredient page of admin UI
**To Reproduce**
1. Go to admin UI
2. Click on Meals
3. Select a specific meal eg: Chicken Curry
4. Select Ingredients
5. The ingredients page does not show which meal it belongs to. 

**Expected behavior**
Meal name should be displayed in the ingredients page like it is shown in a specific ingredient page and match page

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by shanthisa** [comment]
@priyaguntupalli5 - Since the meal name is visible I am approving. Styling of the meal name to left justify and italics like in Match Ingredient view would keep it uniform in all pages. Please do the changes as part of this same ticket.

**Comment by olamakhlouf** [comment]
QA is done 
Test Case [AA-MealNameOnIngredientPage-082](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#082): Passed.
