### ISSUE TITLE
[FEATURE] Meal Plan Card: The user circle should show empty for no user and T with grey for template

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#622]
**Is your feature request related to a problem? Please describe.**
In Meal Plans page, the Meal Plan card currently shows templates and meal plans alike. There is no easy visual differentiator.
We need to visually show a differentiator such as the gravatar circle different for a template, meal plan with no user and meal plan with user assigned.

**Describe the solution you'd like**
Since no user can be assigned to a template, we can show the gravatar circle as grey in colour with T. On hover it can show a tooltip 'Template'.
For a meal plan where the user is not assigned, show the green circle as empty instead of NN because there can be user names such as 'Nigel Nickelson' for which the gravatar circle will show NN. Also, explicitly specifying 'No User Assigned' in place of the User in the meal plan card would add clarity.

**Describe alternatives you've considered**
The earlier options were not clear.

**Comment by ala-sk98** [comment]
Test case [MP-MealPlanAvatar-071](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-MealPlanAvatar-071): Passed
QA is completed. Ready to review @priyaguntupalli5 .

**Comment by priyaguntupalli5** [comment]
Hi @ala-sk98, I reviewed the test cases. For the 6th point, you mentioned that "No User Assigned" should be shown on the tooltip when hovered. I think that was not required. We need it in place of the user on the mealplan card, as per the feature description. Can you please double-check on that?

**Comment by ala-sk98** [comment]
Thanks for the comments, @priyaguntupalli5. It fixed now.
