### ISSUE TITLE
[FEATURE] Favorite icon needs to be removed in meal plan

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#623]
**Is your feature request related to a problem? Please describe.**
We don't need favorite meal plans as we have templates

**Describe the solution you'd like**
Remove Favorites icon from the mealplan card.

**Comment by ala-sk98** [comment]
QA is done.
Test case [MP-RemoveFavoriteIcon-067](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-RemoveFavoriteIcon-067): Passed

**Comment by okayyjen** [comment]
LGTM @shanthisa could you close this issue?

**Comment by shanthisa** [comment]
@ala-sk98 - [MP-MPCalendar-002] should not be a pre-requisite for this test case. Moreover please provide the navigation step as 'Go to /mealplan'

**Comment by olamakhlouf** [comment]
@shanthisa updated the test case
