### ISSUE TITLE
Admin UI: Search for meals is not working as before

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#624]
**Describe the bug**
Search Meals in Admin UI is not working as before. That is it works in the current version of develop.goodmealplan.com:8443 but not in the latest v2 version.

**To Reproduce**
1. Go to admin UI
2. Click on Meals
3. Search for 'bread' 
4. The results are not correct. Please refer screenshots

**Expected behavior**
All the results for the bread like shown in the test server screenshot should appear.

**Screenshots**
Expected result:
In test server,
![image](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/72ff5b82-1c28-4476-8dcc-560e273ab8a6)

Observed result:
In local v2, 
![image](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/8e86e3fb-fde2-451f-bb7d-29778ee9c273)

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] chrome
 - Platform [e.g. IDE, docker-compose, QA site] docker-compose and QA

**Comment by ala-sk98** [comment]
QA is Done. 
Test case [AA-SearchMeals-065](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-SearchMeals-065) : Passed

**Comment by ala-sk98** [comment]
@RLCASTRO : Tast case is now available at the link

**Comment by RLCASTRO** [comment]
Test case reviewed, LGTM 👍 Please close the issue.
