### ISSUE TITLE
[BUG] Unit is missing in the Products grid in Matches view

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#625]
**Describe the bug**
Next to Quantity it will be nice to have the unit displayed in the Matches page of the admin UI
**To Reproduce**
1. Go to 'admin UI'
2. Click on Meals
3. Select a meal
4. Click Ingredients
5. In Ingredients page, select MATCH of an ingredient
6. In the Matches page, you will see the grid of products

**Expected behavior**
It will be good to display the unit next to the quantity in the products table

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by RLCASTRO** [comment]
I'll start working on this. Can you assign it to me @shanthisa?

**Comment by folaj034** [comment]
QA is done.
 

AA-UnitDisplayedNextToQuantityInProductMatch-090

Test case ID: AA-UnitDisplayedNextToQuantityInProductMatch-090

**Comment by folaj034** [comment]
QA is done
Test case  [AA-UnitDisplayedNextToQuantityInProductMatch-090](#090)   : passed

**Comment by folaj034** [comment]
| [AA-UnitDisplayedNextToQuantityInProductMatch-090](#090) |

**Comment by folaj034** [comment]
| [AA-UnitDisplayedNextToQuantityInProductMatch-090](#090) | Verify  the Unit is displayed next to the quantity in the Products Match view. |

**Comment by folaj034** [comment]
| 90 | [AA-UnitDisplayedNextToQuantityInProductMatch-090](#090) |

| 90 | [AA-UnitDisplayedNextToQuantityInProductMatch-090](#090) |

**Comment by folaj034** [comment]
[AA-UnitDisplayedNextToQuantityInProductMatch-090](#090) |

**Comment by folaj034** [comment]
[AA-UnitDisplayedNextToQuantityInProductMatch-090]

**Comment by folaj034** [comment]
| [AA-UnitDisplayedNextToQuantityInProductMatch-090 |

**Comment by folaj034** [comment]
AA-UnitDisplayedNextToQuantityInProductMatch-090](#090)

**Comment by folaj034** [comment]
[AA-UnitDisplayedNextToQuantityInProductMatch-090]

**Comment by folaj034** [comment]
AA-UnitDisplayedNextToQuantityInProductMatch-090

**Comment by folaj034** [comment]
QA is done
Test case   [AA-UnitDisplayedNextToQuantityInProductMatch-090](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#090)  : Passed

**Comment by RLCASTRO** [comment]
Test case reviewed LGTM 👍 @olamakhlouf  or @shanthisa  Please close the issue.
