### ISSUE TITLE
[BUG] Cannot create any two mealplans or templates without page refresh

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#629]
**Describe the bug**

**To Reproduce**
1. Go to mealplanner UI
2. Click on 'Mealplans'
3. Create a template 
4. Create another mealplan or template
5. Cannot create any two continuous mealplans or templates without page refresh

**Expected behavior**
Meal planner should be created properly

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Additional context**
Mealplan gets created when created with a user assigned

**Comment by shanthisa** [comment]
@priyaguntupalli5  - You said the bug was a little different from what was originally stated. Please rewrite the steps to reproduce the bug and update the ticket.

**Comment by priyaguntupalli5** [comment]
Hi @shanthisa, during the QA @olamakhlouf noticed that mealplans can be created when date is assigned. Since I don't have edit access anymore, can you please update the 3rd step of the bug description to create a mealplan without date.

**Comment by olamakhlouf** [comment]
Thanks @priyaguntupalli5  Also there is a bug  when creating a template without tag

**Comment by shanthisa** [comment]
Let's have it simple. 'create a template' is without a date. So need not have mealplan

**Comment by shanthisa** [comment]
If you are saying this bug is not fixed with mealplan without date, then you can mention it as a comment and needs to be fixed. This would basically form a second test case

**Comment by olamakhlouf** [comment]
QA is Done.
Test case [MP-CreateTwoTemplates-073](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-MP-CreateTwoTemplates-073)  : Passed
