### ISSUE TITLE
[BUG] reset password is not working

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#631]
**Describe the bug**
Reset password in admin UI -> Users for any user throws an error "Uncaught (in promise) Error: Response not successful: Received status code 400" in the JS console. Does not redirect in the admin UI page and does not give any response for click of 'Reset password'

**To Reproduce**
1. Go to admin UI
2. Click on Users section
3. Select any user's RESET PASSWORD button
4. Give a password and hit on RESET PASSWORD button
5. No response from the UI, but errors found in JavaScript console.

**Expected behavior**
Reset password should say element updated and should update the password.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA

**Additional context**
This is a showstopper bug.

**Comment by ala-sk98** [comment]
QA is done.
Test case [AA-ResetPassword-066](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-ResetPassword-066): Passed

**Comment by RLCASTRO** [comment]
Test case reviewed. LGTM 👍 Please close the issue
