### ISSUE TITLE
[FEATURE] Terms and conditions page

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#632]
**Is your feature request related to a problem? Please describe.**
A Terms and conditions page that displays a set text and the user needs to click a checkbox 'I read the terms and conditions' and click on Agree. Without which we will not allow access to the app and we will logout.

**Describe the solution you'd like**
As a user atleast one time the user needs to agree to the terms and conditions of the application in their first login. If they are already registered like in our production environment, we need to present it next time they login.

**Additional context**
We need to insert a column terms and conditions flag in users table. This should be set to true when the user agrees. By default it would be false. We need a terms and conditions page with text that displayed and checkbox that says 'I read the terms and conditions' and then a button 'Agree' and button 'Disagree'. If they disagree, they will be logged out. If they agree they will get it. This should only be once for the user not each time of login.

**Comment by shanthisa** [comment]
The terms and conditions should be in this text. You can skip the adult name signature parts.
[Meal Planning Legal Waiver.docx](https://github.com/CivicTechFredericton/mealplanner/files/15435648/Meal.Planning.Legal.Waiver.docx)

**Comment by shanthisa** [comment]
Please refer the latest video for QA which is more than 3 mins. (not the first one) in the Pull Request. Also refer the docx file linked in the comments of this ticket. Please thoroughly do the QA for all url endpoints.

**Comment by olamakhlouf** [comment]
QA is done.
Test cases:
[AA-RegisterNewUser-091](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#091) : Passed.

[MP-TermsPage-092](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#092) :Passed.

[MP-RejectConditions-093](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#093) : Passed.
[MP-AcceptConditions-094](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#094) : Passed

**Comment by RLCASTRO** [comment]
Test case reviewed, LGTM 👍 @olamakhlouf or @shanthisa  Please close the issue.
