### ISSUE TITLE
Shopping list: reason for substitute and type any to be specific

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#637]
I had requested some changes. Please do it as a seperate issue. 
Type for quantity and price.
Reason should be included along with substitute name.

_Originally posted by @shanthisa in https://github.com/CivicTechFredericton/mealplanner/pull/634#pullrequestreview-2001140437_

**Comment by olamakhlouf** [comment]
QA is Done
Test case [MP-DisplaySubstituteReason-079](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#079): passed
Test case [AA-PriceAndQuantityType-080](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#080) : passed
