### ISSUE TITLE
[BUG] Primary ingredient missing when there are substitutes for ingredients in a meal

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#644]
**Describe the bug**
Primary ingredient missing when there are substitutes for ingredients in a meal

**To Reproduce**
1. Go to 'Admin UI'
2. Click on '.Bread and Butter Pudding'
3. Check the ingredients list. This has Butter and Margarine as well as Apricot Jam, Raspberry Jam, Marmalade
4. Go to 'Mealplanner UI'
5. Click on 'Meals'
6. Search for Bread and Butter Pudding
7. Look at the ingredients
8. Butter, Apricot Jam are missing. Both are primary ingredients

**Expected behavior**
All ingredients should be displayed.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by olamakhlouf** [comment]
QA Done 
Test Case [MP-CheckPrimaryIngredient-077](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#077): Passed

**Comment by RLCASTRO** [comment]
Test case reviewed LGTM 👍 @olamakhlouf or @shanthisa Please close the issue.
