### ISSUE TITLE
[FEATURE] Need a link back to Meal from the meal name of the ingredient

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#645]
**Is your feature request related to a problem? Please describe.**
Need a link back to Meal from the meal name of the ingredient

**Describe the solution you'd like**
In Admin UI, when I go to the ingredients list, to navigate back, I would prefer to have the meal name as a link to link back to the meal page.

**Comment by shanthisa** [comment]
@RLCASTRO Thanks for working on this. Looks like the requirement is not met here. The file edited is IngredientEdit. But we need the navigation from Meal name in the IngredientsList page to go to the individual meal show page.

**Comment by olamakhlouf** [comment]
QA is done
Test case [AA-BackToMeal-081](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#081): Passed

**Comment by RLCASTRO** [comment]
Test case reviewed LGTM 👍 @olamakhlouf or @shanthisa Please close the issue.
