### ISSUE TITLE
[FEATURE] Search for product keyword to be not case-sensitive in products

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When the product keyword is with a different case such as 'Butter', it is not matching with the ingredient product keyword which says 'butter'. So it would be good if the search for product keyword of product is not case-sensitive.

**Comment by olamakhlouf** [comment]
QA is done 
test case [AA-NoneCaseSensitiveSearch-103](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#103): Passed.
