### ISSUE TITLE
[BUG] Search product not working for any word in the product name

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#656]
**Describe the bug**
Mohamed found a bug in the search in the admin-ui. It's not performing search by keywords in Products (Meals is working good by keyword). Another problem is when the product has multiple words in the name, which is all of them, you have to type them in the exact sequence, otherwise it won't return a result. for example.
Lets take the product with name = Club House, Dry Sauce/Seasoning/Marinade Mix, 4 Peppercorn Gravy, 31g as an example. If I search for club house it will return this product in the list, but if I search for club peppercorn it will not, it at my head it was supposed to perform the search by any keyword in the name.

**To Reproduce**
Go to admin-ui
click on Products
search for  club peppercorn
it should return all the items with these keywords in the name or other fields. but it doesn't.
To reproduce the issue related to search by keyword
Go to admin-ui
click on Products
`search for search for peppercorns
it will return 1 product that has peppercorns in the name and in the keyword fields
perform the search again with peppercorn in the singular
It will return 3 products with peppercorn in the name but it has peppercorns in the keywords, so it should be returned in the previous search
The conclusion is that the search is not working for the Product Keywords field.

**Expected behavior**
Search should work for any word in the product name.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari]
 - Platform [e.g. IDE, docker-compose, QA site]

**Additional context**

**Comment by olamakhlouf** [comment]
QA is Done
Test Case [AA-SearchProductByAnyWord-078](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#078) : Passed

**Comment by RLCASTRO** [comment]
Test case reviewed, LGTM :+1:  @shanthisa please close the issue.
