### ISSUE TITLE
9.4 Obtain access and credentials to the AWS environment

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#66]

**Comment by Joycelyn2015** [comment]
Sent email to Sandi with the following list of users to be granted access.
1. FName:Mohamed
LName:Hussein
Email: mohameda-hussein@outlook.com

2. FName: Olusayo
LName:Obajemu
Email: sayoobaj@gmail.com

3. FName: Elvina
LName:Cherepovich
Email: elvinacherepovich@gmail.com

4. Fname: Ivy
LName: Cartagenas
Email: teves16@gmail.com

5. FName: Christopher
LName: Salvador
Email: chris.salvador1986@gmail.com

6. FName: David
LName: Wang
Email: gawdzak2@gmail.com

7. FName: Brian
LName: Milthorp
Email: bmilthorp@gmail.com

8. FName: Dan
LName: Nelson
Email: dan.nelson.fred@gmail.com

9. FName: sam
LName: macphee
Email: samueljmacphee@gmail.com

10. FName: sam
LName: ismail
Email: sam.ismail.ca@gmail.com

**Comment by ElvinaCherepovich** [comment]
11.
Fname: Ronen
Lname: Ziv
Email: ronenziv111@gmail.com

**Comment by Joycelyn2015** [comment]
Access to 10 users are granted.

**Comment by Joycelyn2015** [comment]
This is DONE.  Closing now.
