### ISSUE TITLE
[FEATURE] Admin UI: Tips in Meals should be rich text format

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#664]
**Is your feature request related to a problem? Please describe.**
In Admin UI, when there are more than one tips in a recipe, it is not possible to put them as bullet points as it is plain text format.
**Describe the solution you'd like**
In admin UI, the tips should have rich text format just like the method so that if there are more than one tips it can be bulleted.

**Comment by olamakhlouf** [comment]
QA is done.
Test case [AA-TipsInRichText-089](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#089): Passed
