### ISSUE TITLE
[BUG] assign user drop-down visible for client users

### ISSUE THREAD

**Issue by rorybray** [CivicTechFredericton/mealplanner#666]
**Describe the bug**
When logged in as a client user, in "create meal plan", the assign user drop-down is visible even though a client user cannot re-assign plans.

**To Reproduce**
1.Log into mealplanner UI
2. Click on "Create Meal Plan"
3. Notice the Assign User drop-down

**Expected behavior**
The assign user drop-down should not be visible for a client user role.

**Test Environment (please complete the following information):**
 - Firefox and Chrome
 - running in docker-compose locally

**Comment by olamakhlouf** [comment]
QA is done.
Test case [MP-AssignUserForClient-099](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#099): Passed.

**Comment by jon-dalton** [comment]
Ok to close! 👍
