### ISSUE TITLE
[BUG] the copy template icon/button is missing for a client user

### ISSUE THREAD

**Issue by rorybray** [CivicTechFredericton/mealplanner#667]
**Describe the bug**
Client user can create a template meal plan but then cannot copy it (because copy is missing) and so the aren't able to actually use the template.

**To Reproduce**
1. Login to mealplanner UI
2. Click on "Create meal plan template"
3. Complete the template
4. Return to the meal plans page
5. Notice that the copy icon (🗐) is missing.

**Expected behavior**
Copy icon should be present so that the client user can copy their template to a plan.

**Test Environment (please complete the following information):**
 - Firefox and Chrome
 - Running in the docker-compose environment locally.

**Comment by olamakhlouf** [comment]
QA is done.
Test case [MP-CopyIconForClient-095](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#095): passed.
