### ISSUE TITLE
[BUG] Unable to create substitute ingredient relating to a primary ingredient

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#668]
**Describe the bug**
Primary ingredient is not showing the ingredients list of the current meal. Hence unable 
**To Reproduce**
To reproduce:
Go to admin-ui
click on meals
in the search bar, insert rice pilaf
Click over the SHOW button
Select Ingredients
Select Create
Add a new item called Fresh Parsley
Click over the Primary Ingredient and you should be able to see Dried Parsley Flakes among the options, but it does not display this option.

**Expected behavior**
When clicking over the Substitute Ingredient drop down, it should display the correct options to select.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

**Comment by shanthisa** [comment]
It looks like it is showing a list of ingredients of a different meal rather than the same meal.

**Comment by shanthisa** [comment]
Please provide screenshot of the the dried parsley appearing in the list

**Comment by invisible-pvi** [comment]
Sure. I have attached a screenshot of the dried parsley appearing in the list. 
![image](https://github.com/CivicTechFredericton/mealplanner/assets/156869108/0e6d81c7-6c21-45c2-8391-cf9bf2688bb7)

**Comment by shanthisa** [comment]
@invisible-pvi 
—Thanks for your work. I merged it. It satisfied the criteria for people to proceed with the data entry. There are two minor issues which needs to be fixed. The field name should be Primary Ingredient and not Meal. Second, the same ingredient should not appear in the list. For example, milk cannot be a primary ingredient for the ingredient milk. I hope you can work on them. Please let me know if you have any questions. Thanks.

**Comment by invisible-pvi** [comment]
Sure. I will start working on it now.

**Comment by shanthisa** [comment]
By default, the Primary ingredient field should be shown as empty because by mistake, if people just save without noticing that field, the default value shown will be updated as the primary ingredient.
So the requirements are 
1. Default value should be empty and should be possible to save it as empty. That is primary ingredient can be null on save.
2. Whatever value is selected should be saved as the primary ingredient. 

Right now we are facing issues with that with the following error
![image](https://github.com/CivicTechFredericton/mealplanner/assets/57197486/f6924fce-ef49-4be2-ab31-ca3743fa3e32)

**Comment by shanthisa** [comment]
Apart from the top two showstoppers, the other two minor issues are
3. The field name should be Primary Ingredient and not Meal. 
4. The same ingredient should not appear in the list. For example, milk cannot be a primary ingredient for the ingredient milk. 
I hope you can work on them. Please let me know if you have any questions. Thanks.

**Comment by invisible-pvi** [comment]
Sure! I am working on it. I have fixed 3. I am working on fixing 1, 2 and 4.

**Comment by invisible-pvi** [comment]
Hi Shanthi, I have created a pull request for the fixes for 3. For 1, I think removing `not null` for meal_id in the backend/db_migrations/000007_ingredient.up.sql will allow accepting null values. I tried that and it worked out. But the reason I didn't include it in the newer pull request is because the save functionality is not working effectively. Based on the errors received, it seems to me that sql files may need to be changed with the new changes coming in.

**Comment by shanthisa** [comment]
`null value in column "meal_id" of relation "ingredient" violates not-null constraint` error comes when you click on Primary ingredient field and delete it to empty and edit some other field example: quantity and click save.

**Comment by shanthisa** [comment]
I had fixed the main bug. Moving my observation 'The same ingredient should not appear in the list. For example, milk cannot be a primary ingredient for the ingredient milk.' to a different issue as the main aspect of the bug is fixed.

**Comment by folaj034** [comment]
QA done.
Test case  [MP-AA-CreateSubstituteIngredientforPrimaryIngredient-096](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#096)  :Passed

Also confirmed bug 1, 2 3 ( Default value can be empty/null and saved, the selected value can be saved as the primary ingredient, and the field name is now "Primary Ingredient" and not "Meal".

**Comment by folaj034** [comment]
QA done.
Test case [MP-AA-CreateSubstituteIngredientforPrimaryIngredient-096](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#096)  :Passed

Also confirmed bug 1, 2 3 is fixed ( Default value can be empty/null and saved, the selected value can be saved as the primary ingredient, and the field name is now "Primary Ingredient" and not "Meal").

**Comment by shanthisa** [comment]
Please rewrite them as below to be clear and concise:

8. Click on the Primary Ingredient field
9. Select one of the meal's existing ingredient 'Dried Parsley Flakes' among the options.
10. Click Save

Expected Behaviour:
Ingredients page has an ingredient 'Fresh Parsley' with primary ingredient 'Dried Parsley Flakes'

**Comment by folaj034** [comment]
Update done as par comment above.

Test case [MP-AA-CreateSubstituteIngredientforPrmIngredient-096](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#096) : Passed

**Comment by folaj034** [comment]
Updated.  Thank you.

Regards
