### ISSUE TITLE
[BUG]  Unnecessary blank space before the ingredients and method.

### ISSUE THREAD

**Issue by olamakhlouf** [CivicTechFredericton/mealplanner#670]
**Describe the bug**
In the specific meal page, there is an unnecessary blank space before the ingredients and method.

**To Reproduce**
1. Go to 'Mealplanner UI'
2. Click on 'Meals'
3. Click on 'Salsa Cruda' to open the meal page
4. See that there is an unnecessary blank space before the ingredients and method.

**Expected behavior**
The ingredients and method should be displayed right after the meal picture, title, and description without unnecessary blank space.

**Screenshots**
![Screenshot from 2024-05-14 11-29-10](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/68f9d46f-ac51-4e0e-88c0-081fe8b0040b)
![Screenshot from 2024-05-14 11-29-14](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/1ec99cbf-b012-421f-8629-d5b2988e1d23)

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari]
 - Platform [e.g. IDE, docker-compose, QA site]

**Comment by shanthisa** [comment]
@olamakhlouf - approved and merged. Can you please provide a screenshot of the fix in the ticket for reference? Thanks

**Comment by olamakhlouf** [comment]
![Screenshot from 2024-05-15 16-15-39](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/f990235c-2e9a-4551-bda4-e220e43393e8)

**Comment by olamakhlouf** [comment]
QA is done.
Test case [MP-SpaceBeforeMethod-088](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#088): Passed.
