### ISSUE TITLE
[FEATURE]  Print meal plan should have civic tech logo and name

### ISSUE THREAD

**Issue by olamakhlouf** [CivicTechFredericton/mealplanner#673]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As a user/admin/meal designer, I would like to see the Civic Tech logo and name in the printout of the meal plan so that they know who has created them :-)

**Comment by cybernetrho** [comment]
QA is done.
Test case [MP-CivictechLogOnMealPlan-084](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#084): Passed
