### ISSUE TITLE
[FEATURE] Change in the Ingredients Table Structure. 

### ISSUE THREAD

**Issue by invisible-pvi** [CivicTechFredericton/mealplanner#681]
**Is your feature request related to a problem? Please describe.**
In the MealPlanner UI, when a specific meal is selected, the ingredients table for the meal should display the substitute ingredient right after the primary ingredient (not at the end.)

**Describe the solution you'd like**
As a user, whenever I click on a meal to view the ingredients, I should be able to view the substitute ingredient right after its primary ingredient in the ingredients table.

**Comment by shanthisa** [comment]
Isn't this the same issue that is already addressed by Rodrigo in #688 ? If yes we can close this issue

**Comment by invisible-pvi** [comment]
Yes sure.
