### ISSUE TITLE
[BUG] Create New Template should not be appearing for app_user

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#687]
**Describe the bug**
Currently the create new mealplan template is appearing for the client which has the app_user role. Create Template is required only for admins and meal designers

**To Reproduce**
1. Login to 'mealplanner UI' as a client user
2. Click on 'Meal Plans'
3. Click on 'Create New Meal Plan'

**Expected behavior**
 The option to 'Create Template' should not appear for the client user.

**Comment by olamakhlouf** [comment]
QA is done.
Test case [MP-ClientCanNotCreateTemplate-100](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#100) : passed
