### ISSUE TITLE
[BUG]  the tips appears with the HTML tags

### ISSUE THREAD

**Issue by olamakhlouf** [CivicTechFredericton/mealplanner#704]
**Describe the bug**
On Admin UI, the tips appears with the HTML tags

**To Reproduce**
1. Go to Admin UI
2. Click on 'Tuna Noodle Casserole' Meal
3. Click on the "Summary" tab.
4. Scroll Down to "tips" part
5. Edit the tips and format it in points then save 
6. See the HTML tags displayed instead of bulletins points

**Expected behavior**
The tips should be shown bulletins points

**Screenshots**

![Screenshot from 2024-05-31 10-45-23](https://github.com/CivicTechFredericton/mealplanner/assets/99453690/9174d856-3153-478d-b79a-83ab41943a65)

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari]
 - Platform [e.g. IDE, docker-compose, QA site]

**Additional context**

**Comment by shanthisa** [comment]
It is always a good practice to show a screenshot after the fix to show that the bug is fixed with your change. @jon-dalton Please attach a screenshot. Thanks.

**Comment by olamakhlouf** [comment]
QA is done.
Test case [AA-TipsInRichText-089](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#089): Passed

**Comment by jon-dalton** [comment]
Ok to close! 👍
