### ISSUE TITLE
[FEATURE] Tags in meal plan and meal should be ordered in alphabetical order when displayed

### ISSUE THREAD

**Issue by shanthisa** [CivicTechFredericton/mealplanner#707]
**Is your feature request related to a problem? Please describe.**
Currently when there are many tags it is dfficult to read and find the one. 
**Describe the solution you'd like**
So we need to alphabetically order the tags in both meals and meal plans

**Describe alternatives you've considered**
Filter by tag name with autocompletion. Dropped it as it reqquires time.

**Comment by olamakhlouf** [comment]
QA is done.
test case [MP-TagsOrderedAlphabetical-044](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#044): passed
