### ISSUE TITLE
Implementing classes model in Python - User, Designer

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#74]
Sayoobaj

**Comment by ElvinaCherepovich** [comment]
Meal planner Data model diagram is here 
https://drive.google.com/file/d/1iUM-tG41QntX_E00g3FxYm9ruNyJ6NZG/view?usp=sharing .

**Comment by ElvinaCherepovich** [comment]
11 Feb - 50% of Data Model is implementing!

**Comment by Joycelyn2015** [comment]
Finished the python codes for the class models - Client, Designer

**Comment by Joycelyn2015** [comment]
This is DONE.  Closing now.
