### ISSUE TITLE
6.5 Create Domain Name for Meal Planner

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#75]

**Comment by Joycelyn2015** [comment]
Sent message to the team asking for suggestions. 
Bam might need to ask the client if they have a preferred name.

**Comment by ElvinaCherepovich** [comment]
Here is the list of domain names:

1. www.goodmeals.com
2. www.goodmealplan.com
3. gvplanner.com
4. mealplannerfitness.com 
5. mealplanner.greenvillage.org

**Comment by ElvinaCherepovich** [comment]
Sandi is agreed with www.goodmealplan.com :)

**Comment by Joycelyn2015** [comment]
This is DONE.  Closing now.
