### ISSUE TITLE
Create a plan of meals

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#8]
Client or Admin should have opportunity to build a plan of meals from 1 to 4 weeks. 

All plans a personal, however an admins' plan of meal can be used as a systems' template in a client workspace.  The system template might be build for different preferences (halal, gluten free...)

Clients' workspace should have a history of plans which are available for editing by creating new a version of that plan. (new GUID).

**Comment by Joycelyn2015** [comment]
Duplicate of ticket 1.1 Add Meal Plan
