### ISSUE TITLE
Page of a plan

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#80]
1. Mockups will be developed by the responsible analyst @Joycelyn2015 

2. The data model is here https://www.draw.io/#G1iUM-tG41QntX_E00g3FxYm9ruNyJ6NZG 
Related objects:

1. Plan
2. Week
3. Day
4. Shopping list
5. Meal
6. Category 
7. User

3. A.criteria: 
The page contains data about the plan like 

- [ ] -  7 days from Monday to Sanday (lines) 
- [ ] - each day has a type of meal (columns): 
+Breakfast
+Lunch
+Dinner
+Snack
+Breads
+Beverage

**Comment by ElvinaCherepovich** [comment]
Related to User story  #10

**Comment by Joycelyn2015** [comment]
Need to get Albert involved in completing this task.

**Comment by Joycelyn2015** [comment]
This is DONE/COMPLETED.  Closing now.
