### ISSUE TITLE
Page of meal/recipe 

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#81]

**Comment by Joycelyn2015** [comment]
David will work on this.  By April 28, David would have: 
1. updated this ticket and provide description of task
2. discussed with Dan/Albert about the issue he is encountering
3. will show the team what he is working on; it does not have to be finished/completed, we just want everyone to be aware about this task and avoid duplication of task.

**Comment by Gawdzak** [comment]
Create page where the catalog of meals are shown. The user should be able to view the different meal options and its details.

**Comment by Joycelyn2015** [comment]
This is DONE/COMPLETED.  Closing now.
