### ISSUE TITLE
Dashboard page - Meal Designer

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#83]
**As meal designer (/meal assigner), I should have a "hub" or "Dashboard" where I can easily navigate between the functions available to me and see high level information about the program, so I can more easily perform my role.**

**Ability to access**
Client management (includes create new client, assign meal plans to clients)
Catalogue managment (navigate to catalogue of meals, plans, ingredients/products, units)

**Quick access Shortcuts:**
Create a new client
Create a new Meal
Create a new plan
Search bar - clients, meals, plans, products

{{FUTURE}} ? With multiple meal designers, will there be a need to easily access plans and meals for which I am an author?

Data model objects: N/A

Mockup:
**screen below is out of date - refer to XD wireframe**
 ![Mealplanner dashboard.png](https://images.zenhubusercontent.com/5df03594ae8d3367aa8aeff9/2ed43a01-ed2e-47f8-a352-bbe9b13a37c6)

**Comment by ivzgrace** [comment]
Here is the wireframe link in progress https://xd.adobe.com/view/904293fd-dfcd-443a-6c9a-5319a6c3c2bc-e673/screen/1aa03f84-528d-4d62-8eb3-1f317a6abcf3/Dashboard?fullscreen

**Comment by Joycelyn2015** [comment]
This is DONE/COMPLETED.  Closing now.
